# Gambas Action File 3.0

{ Actions
  { Action NewTab
    Text = "New Query"
    Shortcut = "Ctrl+N"
    Picture = "icons/16/ResultTab.png"
  }
  { Action Run
    Text = "Run query"
    Picture = "icons/16/Query.png"
  }
}

