# Gambas Action File 3.0

{ Actions
  { Action AddRow
    Text = "Add row"
    Picture = "icon:/16/add"
  }
  { Action Edit
    Text = "Edit"
    Picture = "icons/16/Edit.png"
  }
  { Action ExecuteStatements
    Text = "Save to file"
    Picture = "icon:/16/save"
  }
  { Action Lock
    Text = "Lock"
    Picture = "icons/16/Lock.png"
  }
  { Action Refresh
    Text = "Refresh"
    Picture = "icons/16/Refresh.png"
  }
  { Action RemoveRow
    Text = "Remove row"
    Picture = "icon:/16/remove"
  }
}

