# Gambas Action File 3.0

{ Actions
  { Action DeleteDatabase
    Text = "Delete Database"
    Picture = "icon:/16/remove"
  }
  { Action DeleteItem
    Text = "Delete Item"
    Shortcut = "Ctrl+Del"
    Picture = "icon:/16/trash"
  }
  { Action EditItem
    Text = "Edit Item"
    Shortcut = "Ctrl+E"
    Picture = "icon:/16/edit"
  }
  { Action Lock
    Text = "Lock"
    Picture = "icons/16/Lock.png"
  }
  { Action NewDatabase
    Text = "New Database"
    Picture = "icons/16/Database.png"
  }
  { Action NewItem
    Text = "New Item"
    Shortcut = "F2"
    Picture = "icons/16/New.png"
  }
  { Action Refresh
    Text = "Refresh"
    Shortcut = "F5"
    Picture = "icons/16/Refresh.png"
  }
}

