' Gambas module file

Public Sub Main()

  Dim repo As Repository

  Object.Attach(Git, Me, "Git")
  If Not Exist("/home/adrien/Programmation/Gambas/src/gambas-gb.git/") Then
    repo = Git.Clone("https://gitlab.com/gambas/gambas.git", "/home/adrien/Programmation/Gambas/src/gambas-gb.git/")
  Else
    repo = Git.Open("/home/adrien/Programmation/Gambas/src/gambas-gb.git/")
  Endif

  Print repo.Path
  Print repo.Workdir

  Print "===="

  InfoCommit(repo.Head)
  Status(repo)

Catch
  Error Error.Text
End

Public Sub Status(repo As Repository)

  Dim s As GitStatus = repo.Status()
  Print "===="

  For Each s
    If s.Ignored Then Continue
    Print "S:";; s.Path;; s.StatusString
  Next

End

Public Sub InfoCommit(commit As GitCommit)

  Print "ID: "; commit.Id
  Print "Date: "; commit.Date
  Print "Summary: "; commit.Summary

End


Public Sub Git_Transfer()

  Print Chr(27); "[2K\r";; Round(Git.Transfer.ReceivedObjects / Git.Transfer.TotalObjects * 100); "%";;
  Print Git.Transfer.ReceivedObjects; "/"; Git.Transfer.TotalObjects; " objects ";
  Print Git.Transfer.ReceivedBytes; " received at "; Git.Transfer.Speed;

End

