' Gambas module file

Private hSCan As Scanner


Public Sub main()
  
  
  Dim s As String
  
  hSCan = New Scanner("hpaio:/net/HP_LaserJet_MFP_M426fdn?ip=192.168.1.25")
  
  For Each s In hSCan
    If hSCan[s].IsRange Then 
      Print "IsRange : ", s, " ", "==>", "min : ", hSCan[s].MinValue, "Max :", hSCan[s].MaxValue, "Units : ", hSCan[s].Unit
    Else
      Print "IsList : ", s, " ", "==>", hSCan[s].List.Join()
    Endif
  Next
  
End
