' Gambas module file

Library "libgit2"

Public Const GIT_OID_HEXSZ As Integer = 40
Public Const GIT_OID_RAWSZ As Integer = 20

Extern git_oid_fmt(out As Pointer, id As Pointer)

Public Sub Format(oid As Pointer) As String

  Dim buf As Pointer = Alloc(1, GIT_OID_HEXSZ)
  Dim out As String

  git_oid_fmt(buf, oid)
  out = String@(buf, GIT_OID_HEXSZ) & ""

  Free(buf)
  Return out

End

Public Sub New() As Pointer

  Return Alloc(1, GIT_OID_RAWSZ)

End

Public Sub Free(oid As Pointer)

  Free(oid)

End
