' Gambas module file

Export

Public Sub MkDir(Path As String)

  Dim sElt As String
  Dim sMake As String = "/"

  For Each sElt In Split(Path, "/")
    sMake &/= sElt
    If IsDir(sMake) Then Continue
    Try Mkdir sMake
  Next

End

Public Sub RmDir(Path As String)

  Dim sFile As String
  
  For Each sFile In Dir(Path)
    If IsDir(Path &/ sFile) Then
      RmDir(Path &/ sFile)
    Else
      Kill Path &/ sFile
    Endif
  Next
  
End

Public Sub Move(Source As String, Destination As String)
  
  If IsDir(Destination) Then Destination &/= File.Name(Source)
  
  Try Move Source To Destination
  If Error Then
    Copy Source To Destination
    Kill Source
  Endif
  
End
