' Gambas module file

Public Sub Main()

  Dim a As New Memcached

  Dim b As Collection

  Dim c As String

  Dim d As Boolean

  '
  ' a.Debug = True
  '
  a.Open()

  'Print a.Version

  ' a.Flush()
  '

  a["asd"].Value = "val1"

  c = a["asd"].Value

  a["asd"].Value = "val2"

  d = a["asd"].Cas("asd")

  'a["asd"].Value = "val2"

  ' a["asd1"].Value = "valasd1"
  '
  ' a["asd2"].Value = "valasd2"
  ' a["asd3"].Value = "valasd3"
  '
  'b = a.Get(["add", "asd", "asd3", "add", "asd", "asd1", "add", "asd", "asd2"])

  a.Close()

End
