' Gambas module file

Public Sub Main()

  Dim a As New Memcached

  Dim b As Collection

  Dim c As Float

  Dim d As Boolean

  '
  ' a.Debug = True
  '
  a.Open()

  'Print a.Version

  ' a.Flush()

  a["asd"].Value = 5

  Debug a["asd"].Value = 5

  c = a["asd"].Value

  a["asd"].Increment(3)

  Debug a["asd"].Value = c + 3

  a["asd"].Decrement(3)

  Debug a["asd"].Value = c

  a["asd"].Value = "asd"

  Debug a["asd"].Value = "asd"
  '
  ' a["asd"].Value = "val1"

  ' c = a["asd"].Value

  ' a["asd"].Value = "val2"

  'c = a["asd"].Value

  'd = a["asd"].Cas("asd")

  'a["asd"].Value = "val2"

  ' a["asd1"].Value = "valasd1"
  '
  ' a["asd2"].Value = "valasd2"
  ' a["asd3"].Value = "valasd3"
  '
  'b = a.Get(["add", "asd", "asd3", "add", "asd", "asd1", "add", "asd", "asd2"])

  a.Close()

End
