' Gambas module file

Public Const FORM As String = "text/x-gambas-form"
Public Const CONTROL As String = "text/x-gambas-control"
Public Const FILE As String = "text/x-gambas-file"
Public Const URI As String = "text/uri-list"
Public Const DATA As String = "text/x-gambas-data"
Public Const CLASS As String = "text/x-gambas-class"
Public Const LIST As String = "text/x-gambas-list"
Public Const MENU As String = "text/x-gambas-menu"
Public Const TABLE As String = "text/x-gambas-table"

Private $cFormat As New Collection

Public Sub _init()
  
  $cFormat["text/plain"] = ("Plain text")
  $cFormat["text/html"] = ("HTML text")
  $cFormat[FORM] = ("Gambas form data")
  $cFormat[MENU] = ("Gambas menu data")
  $cFormat[FILE] = ("Gambas project file path")
  $cFormat[URI] = ("URI list")
  
End

Public Sub GetName(sFormat As String) As String
  
  Dim sName As String = $cFormat[sFormat]
  
  If sName Then 
    Return sName
  Else
    Return ("Unknown format") & " (" & sFormat & ")"
  Endif
  
End

Public Sub UnEscapeURI(URL As String) As String
  
  Dim iInd As Integer
  Dim sRes As String
  Dim sCar As String
  
  For iInd = 1 To Len(URL)
    sCar = Mid$(URL, iInd, 1)
    If sCar = "%" Then 
      sCar = Chr$(Val("&H" & Mid$(URL, iInd + 1, 2)))
      iInd += 2
    Else If sCar = "+" Then 
      sCar = " "
    Endif
    sRes &= sCar
  Next

  Return sRes  
  
End
