' Gambas module file

Public Const FORM As String = "text/x-gambas-form"
Public Const CONTROL As String = "text/x-gambas-control"
Public Const FILE As String = "text/x-gambas-file"
Public Const URI As String = "text/uri-list"
Public Const DATA As String = "text/x-gambas-data"
Public Const CLASS As String = "text/x-gambas-class"

Private $cFormat As New Collection

Public Sub _init()
  
  $cFormat["text/plain"] = ("Plain text")
  $cFormat["text/html"] = ("HTML text")
  $cFormat[FORM] = ("Gambas form data")
  $cFormat[FILE] = ("Gambas project file path")
  $cFormat[URI] = ("URI list")
  
End

Public Sub GetName(sFormat As String) As String
  
  Dim sName As String = $cFormat[sFormat]
  
  If sName Then 
    Return sName
  Else
    Return ("Unknown format") & " (" & sFormat & ")"
  Endif
  
End

