' Gambas module file

Private $sPath As String
Private $bRename As Boolean

Public Sub Begin(sPath As String)
  
  $bRename = False
  $sPath = sPath
    
  Try Kill sPath & "~"
  Move sPath To sPath & "~"
  
  $bRename = True

End

Public Sub End()
  
  Project.Tree.RefreshKey($sPath)
  Project.Tree.SelectKey($sPath)
  $sPath = ""
  $bRename = False
  
End


Public Function Error() As Boolean
  
  Dim sError As String
  
  sError = Error.Text & " (" & Error.Where & ")"
  Debug sError
  
  If $bRename Then 
    Try Move $sPath & "~" To $sPath
  Endif
  
  FMain.ShowError("<b>" & ("Cannot save file !") & "</b>\n\n" & sError, $sPath)
  Try Save.End
  Return True
  
End

