' Gambas module file

Private $sPath As String
Private $bRename As Boolean

Public Sub Begin(sPath As String)
  
  $bRename = False
  $sPath = sPath
    
  Try Kill sPath & "~"
  Move sPath To sPath & "~"
  
  $bRename = True

End

Public Sub End()
  
  Project.RefreshKey($sPath)
  Project.SelectKey($sPath)
  $sPath = ""
  $bRename = False
  
End


Public Function Error() As Boolean
  
  Dim sError As String
  
  sError = Error.Text & " (" & Error.Where & ")"
  
  If $bRename Then 
    Try Move $sPath & "~" To $sPath
  Endif
  
  FGambas.Error(("Cannot save file !") & "\n\n" & $sPath & "\n\n" & sError)
  Save.End
  Return True
  
End

