' Gambas module file

Private Sub Copy(sSrc As String, sDest As String) As Boolean

  Print sSrc; " ==> "; sDest
  Try Copy sSrc To sDest
  If Error Then
    Print "*ERROR*"
    Return True
  Endif

End

Public Sub Main()
  
  Dim hFile As File
  Dim sLine As String
  Dim aLine As String[]
  Dim sIcon As String
  Dim sPath As String
  Dim sTheme As String
  Dim sSize As String
  Dim sTemplate As String
  Dim sExt As String
  Dim sSrc As String
  
  hFile = Open "~/gambas/3.0/trunk/comp/src/gb.form/map/gnome.map"
  
  Try Mkdir "~/gambas/3.0/trunk/comp/src/gb.form.stock/stock/16"
  Try Mkdir "~/gambas/3.0/trunk/comp/src/gb.form.stock/stock/22"
  Try Mkdir "~/gambas/3.0/trunk/comp/src/gb.form.stock/stock/32"
  Try Mkdir "~/gambas/3.0/trunk/comp/src/gb.form.stock/stock/scalable"
  
  While Not Eof(hFile)
  
    Line Input #hFile, sLine
    aLine = Scan(sLine, "* *")
    If aLine.Count < 2 Then Continue
    sIcon = aLine[0]
    If Left(sIcon) = ";" Then Continue
    sPath = Trim(aLine[1])
    If Not sPath Then Continue
    sPath = Split(sPath, ";")[0]
    
    Print sIcon
    
    For Each sSize In ["16", "22", "32", "scalable"]
      
      'Try Kill "~/gambas/3.0/trunk/comp/src/gb.form.stock/stock" &/ sSize &/ sIcon & ".png"
      'Try Kill "~/gambas/3.0/trunk/comp/src/gb.form.stock/stock" &/ sSize &/ sIcon & ".svg"
      
      For Each sTheme In ["elementary/&2/&1", "Tango/&1/&2", "gnome/&1/&2", "hicolor/&1/&2"]
    
        sTemplate = "/usr/share/icons" &/ sTheme
    
        If sSize = "scalable" Then
          sExt = ".svg"
          If Copy(Subst(sTemplate, sSize, File.Dir(sPath)) &/ File.SetExt(File.Name(sPath), sExt), "~/gambas/3.0/trunk/comp/src/gb.form.stock/stock" &/ sSize &/ sIcon & sExt) Then
            Copy(Subst(sTemplate, "16", File.Dir(sPath)) &/ File.SetExt(File.Name(sPath), sExt), "~/gambas/3.0/trunk/comp/src/gb.form.stock/stock" &/ sSize &/ sIcon & sExt)
          Endif
        Else
          sExt = ".png"
          If Copy(Subst(sTemplate, sSize, File.Dir(sPath)) &/ File.SetExt(File.Name(sPath), sExt), "~/gambas/3.0/trunk/comp/src/gb.form.stock/stock" &/ sSize &/ sIcon & sExt) Then
            Copy(Subst(sTemplate, sSize & "x" & sSize, File.Dir(sPath)) &/ File.SetExt(File.Name(sPath), sExt), "~/gambas/3.0/trunk/comp/src/gb.form.stock/stock" &/ sSize &/ sIcon & sExt)
          Endif
        Endif
    
      Next
    Next
  
  Wend
  
  Close #hFile
  
End

