' Gambas module file

Private $cIconMap As New Collection

Private Sub LoadMap(sMap As String)
  
  Dim hFile As File
  Dim sLig As String
  Dim aMap As String[]
  Dim cMap As New Collection

  If $cIconMap.Exist(sMap) Then Return

  hFile = Open "map" &/ sMap & ".map"
  While Not Eof(hFile)
    Line Input #hFile, sLig
    sLig = Trim(sLig)
    If Left(sLig) = "'" Or Left(sLig) = "#" Then Continue
    aMap = Scan(sLig, "* *")
    If aMap.Count >= 2 Then
      cMap[aMap[0]] = aMap[1]
    Endif
  Wend
  Close #hFile
  
  $cIconMap[sMap] = cMap
    
End


Sub Main()
  
  Dim sPath As String
  Dim cMap As Collection
  Dim sSize As String
  Dim sSrc As String
  Dim sDest As String
  Dim sRoot As String
  
  sRoot = "/home/benoit/gambas/2.0/trunk/gb.qt/src/gb.qt"
  
  Try Mkdir sRoot &/ "default"
  
  LoadMap("kde")
  cMap = $cIconMap["kde"]
  
  For Each sSize In ["16", "32", "48", "64"]
    Try Mkdir sRoot &/ "default" &/ sSize
    For Each sPath In cMap
      Print cMap.Key
      sSrc = "/usr/share/icons/crystalsvg/" & sSize & "x" & sSize &/ sPath
      If Not Exist(sSrc) Then Continue
      sDest = sRoot &/ "default" &/ sSize &/ cMap.Key & ".png"
      Try Kill sDest
      Copy sSrc To sDest
    Next
  Next
  
End
