' Gambas module file

Public Sub Main()

  ' Dim hClient As New SmtpClient
  
  ' hClient.Host = "smtp.gmail.com"
  ' hClient.Encrypt = Net.SSL
  ' hClient.User = "benoit.minisini@gmail.com"
  ' Print "Password:"
  ' Line Input hClient.Password
  ' hClient.Debug = True
  ' 
  ' hClient.Subject = "Test d'un sujet en UTF-8: == l'histoire d'un tout petit bébé =="
  ' hClient.From = "benoit@minisini.fr"
  ' hClient.To.Add("Benoît Minisini <benoit.minisini@gmail.com>")
  ' hClient.Body = "This is a test e-mail.\nI hope it will work...\n\nIl était une fois un tout petit bébé   \n=====\nJOLI HISTOIRE.\n  Il y a une pièce jointe !"
  ' hClient.Add(File.Load("~/TexteDehorsilpleut.odt"), "application/vnd.oasis.opendocument.text", "Dehors il pleut.odt")
  ' hClient.Add(File.Load("~/balloon.png"), "image/png", "balloon.png")
  ' hClient.Send
  
  Dim hMsg As New SmtpClient
  
  ' Dim sChallenge As String
  ' Dim sKey As String
  ' Dim sCommand As String
  ' Dim sResult As String
  ' 
  ' sChallenge = "'abc'"
  ' sKey = "benoit"
  ' 
  ' sCommand = "echo -n " & Shell$(sChallenge) & " | openssl md5 -hmac " & Shell$(sKey)
  ' Shell sCommand To sResult
  ' Print sResult
  ' 
  ' sCommand = "openssl md5 -hmac " & Shell$(sKey) & " << EOF\n'abc'"
  ' Shell sCommand To sResult
  ' Print sResult
  ' 
  ' Return
  
  hMsg.Debug = True
  hMsg.To.Add("benoit@minisini.fr")
  hMsg.Subject = "Test mail #2"
  hMsg.Add("Something" & "\n\n" & ("-- \nPowered by ") & Application.Name & "\n")
  hMsg.From = "benoit.minisini@gmail.com"
  'hMsg.Host = "smtp.free.fr"
  hMsg.Host = "smtp.gmail.com"
  hMsg.Encrypt = Net.TLS
  hMsg.User = "benoit.minisini@gmail.com"
  hMsg.Password = "*****"
  'hMsg.Port = 587
  
  Try hMsg.Send()
  If Not Error Then
    Print "Send successfully"
  Else
    Print "Send Failed: "; Error.Text
  Endif


  ' hMsg.To.Add("unknown@unknown.com")
  ' hMsg.Subject = "Subject"
  ' hMsg.From = "unknown@unknown.nl"
  ' hMsg.Host = "127.0.0.1"
  ' hMsg.Port = 465
  ' 
  ' hMsg.Add("Body Text")
  ' 
  ' hMsg.User = "username"
  ' hMsg.Password = "password"
  ' hMsg.Encrypt = Net.SSL
  ' 
  ' Try hMsg.Send()
  ' If Not Error Then
  '   Print "Send successfully"
  ' Else
  '   Print "Send failed: " & Error.Text
  ' Endif

End


