' Gambas module file

Private $hConn As New Connection

Public Sub Main()

  Dim rTest As Result
  Dim aText As String[]

  $hConn.Type = "mysql"
  $hConn.User = "root"
  '$hConn.Name = "dbsqlite.db"
  $hConn.Name = "test"
  '$hConn.Host = "/home/benoit"

  ' $hConn.Open
  ' 
  ' aText = ["la nuit est", "un long fleuve", "tranquille", "qui dort le long", "des pleurs infidèles"]
  ' DB.Begin
  ' rTest = DB.Edit("test")
  ' For Each rTest
  '   rTest!comment = aText.Copy(0, Int(Rnd(1, aText.Count))).Join("\n")
  '   rTest.Update
  ' Next
  ' DB.Commit

  'DB.Debug = TRUE

  'Application.Theme = "gnome"

  FTest.Show

End
