' Gambas module file

Public Sub Main()

Dim writer As New XmlWriter

  
writer.Open("", True)


writer.StartElement("toto")
writer.StartElement("titi")
writer.Attribute("titi", "tutu\ntoto")
writer.Text("h<&ello")
writer.EndElement()
writer.StartElement("titi")
writer.Text("hello")
writer.EndElement()
writer.Element("toto", "hello")
writer.StartElement("titi")
writer.Text("hello")
writer.EndElement()
writer.Element("toto", "hello")
writer.StartElement("titi")
writer.Text("hello")
writer.EndElement()

writer.EndDocument()

Print writer.Data

End
