# Gambas Action File 3.0

{ Actions
  { Action a
    Text = ""
    Picture = "icon:/22/bookmark"
  }
  { Action b
    Text = ""
    Picture = "icon:/22/computer"
  }
  { Action c
    Text = ""
    Picture = "icon:/22/edit"
  }
  { Action d
    Text = ""
    Picture = "icon:/22/component"
  }
}

{ Toolbars
  { Toolbar test
    Text = ""
    List = "a,b,c,d"
    Default = "a,|,d"
  }
}

