# Gambas Action File 3.0

{ Actions
  { Action workspace-close
    Text = "Close tab"
    Shortcut = ""
    Picture = "icon:/small/close"
  }
  { Action workspace-close-all
    Text = "Close all tabs"
    Shortcut = ""
  }
  { Action workspace-close-other
    Text = "Close other tabs"
    Shortcut = ""
  }
  { Action workspace-close-right
    Text = "Close tabs on the right"
    Shortcut = ""
  }
  { Action workspace-next-tab
    Text = "Next tab"
    Shortcut = "Ctrl+PgDown"
  }
  { Action workspace-previous-tab
    Text = "Previous tab"
    Shortcut = "Ctrl+PgUp"
  }
  { Action workspace-sort-tab
    Text = "Sort tabs"
    Shortcut = ""
    Picture = "icon:/small/sort-ascent"
  }
}

