INCLUDE(FindPkgConfig OPTIONAL)

IF(PKG_CONFIG_FOUND)

    INCLUDE(FindPkgConfig)

    PKG_CHECK_MODULES(GTK2 gtk+-2.0)

    IF(WIN32)
        PKG_CHECK_MODULES(GTKGL2 gtkglext-win32-1.0)
    ELSE()
        PKG_CHECK_MODULES(GTKGL2 gtkglext-1.0)
    ENDIF()

ENDIF()