######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 13 23:39:19 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CXSLT.h
SOURCES += \
    main.cpp \
    CXSLT.cpp
