' Gambas module file

Public Sub Main()

  Dim aVal As Variant[]
  Dim hSignal As DBusSignal

  'DBus["org.kde.kmail"]["/kmail/kmail_mainwindow_1"].geometry = [0, 24, 1024, 768] '.Get("", "rect")
  'aRect = DBus["org.kde.kmail"]["/kmail/kmail_mainwindow_1", "com.trolltech.Qt.QWidget"].geometry
  'Get("com.trolltech.Qt.QWidget", "rect")

  'DBus.Session._Introspect("org.kde.kmail", "/kmail/kmail_mainwindow_1")
  ' aRect = DBus.Session.CallMethod("org.kde.kmail", "/kmail/kmail_mainwindow_1", "", "Get", "ss", "(iiii)", ["com.trolltech.Qt.QWidget", "rect"])
  ' For iInd = 0 To aRect.Max
  '   Error aRect[iInd];;
  ' Next
  ' Error

  'Print DBus["org.kde.kmail"]["/kmail/kmail_mainwindow_1"].geometry  '"turlutu"
  'Debug aRect
  'Print DBus["system://org.freedesktop.Hal"]["/org/freedesktop/Hal/Manager", "org.freedesktop.Hal.Manager"].GetAllDevices().Join("\n")
  'Print DBus["org.kde.krunner"]["/"].Children.Join("\n")
  'Print DBus["org.kde.krunner"]["/"]._Introspection

  'Print DBus.Session._Name
  'Dim hTest As CTest = CTest
  
  ' Dim cInts As Collection = ["image_path": "/usr/share/icons/gnome/48x48/actions/add.png"]
  ' DBus["org.freedesktop.Notifications"]["/org/freedesktop/Notifications"].Notify("MyApp", 0, "", "PoissonTChat", "Fabien: Chu la ! <a href=\"http://gambaslinux.forumactif.net\">ici</a>", ["test"], cInts, 1000)
  ' 
  ' Debug DBus.Session.Applications.Join("\n")
  ' 
  'DBus.Debug = True
  'DBus.Session.Register(CTest, "/Test", ["org.mpris.MediaPlayer2", "org.mpris.MediaPlayer2.Player"])
  
  DBus.Name = "org.mpris.MediaPlayer2.xt7"
  DBus.Session.Register(CTest2, "/org/mpris/MediaPlayer2", ["org.mpris.MediaPlayer2", "org.mrpris.MediaPlayer2.Player"])

  'Wait 10
  '
    
  'aVal = DBus["org.freedesktop.Notifications"]["/org/freedesktop/Notifications"].GetServerInformation()
  'Print aVal[0];; aVal[1];; aVal[2]
  'Print DBus["system://org.freedesktop.UDisks"]["/"].Children
  
  'hSignal = New DBusSignal(DBus.Session, "org.freedesktop.DBus") As "MySignal"
  ' hSignal = New DBusSignal(DBus.Session, "", True) As "MySignal"
  'Wait 30

  'DBus.Session.Unregister(CTest)
  
End

Public Sub MySignal_Signal(Method As String, Arguments As Variant[])
  
  Debug Method
  
End
