' Gambas module file

Public Sub Main()
  
  ' Session["login"] = "cartable"
  ' Session["password"] = "test"
  ' Session["date"] = Date(1972, 9, 6)
  ' Session["age"] = 34
  ' Session["taille"] = 1.72
  ' Session["liste"] = ["bleu", "blanc", "rouge"]

  'Print Session["liste"].Join(" ")
  
  Session.Id = "C9FDEB40ADF2203502B959BC6039BBB4@"
  'Session["liste"] = ["bleu", "blanc", "rouge"]
  Print Session["liste"].Join(" ")
 
End

Public Sub Log(sMsg As String)
  
  Dim hFile As File
  
  hFile = Open "/tmp/session.log" For Append 
  Print #hFile, sMsg
  Close #hFile
  
End
