' Gambas module file

Export

Property MaxAge As Integer
Property ProxyMaxAge As Integer
Property {Public} As Boolean
Property NoCache As Boolean
Property NoStore As Boolean
Property MustRevalidate As Boolean
Property ProxyRevalidate As Boolean

Private Function MaxAge_Read() As Integer

  

End

Private Sub MaxAge_Write(Value As Integer)

  

End

Private Function ProxyMaxAge_Read() As Integer

  

End

Private Sub ProxyMaxAge_Write(Value As Integer)

  

End

Private Function NoStore_Read() As Boolean

  

End

Private Sub NoStore_Write(Value As Boolean)

  

End

Private Function MustRevalidate_Read() As Boolean

  

End

Private Sub MustRevalidate_Write(Value As Boolean)

  

End

Private Function ProxyRevalidate_Read() As Boolean

  

End

Private Sub ProxyRevalidate_Write(Value As Boolean)

  

End
