' Gambas module file

EXPORT

PROPERTY READ Host AS String
PROPERTY READ Root AS String
PROPERTY READ Request AS String
PROPERTY LogFile AS String
PROPERTY Protocol AS String
 
PRIVATE $sLogFile AS String
PRIVATE $hLogFile AS File
PRIVATE $sProtocol AS String = "http"

PRIVATE FUNCTION Host_Read() AS String

  RETURN CGI["HTTP_HOST"]

END

PRIVATE FUNCTION Request_Read() AS String

  DIM sReq AS String
  
  sReq = $sProtocol & "://" & CGI["HTTP_HOST"] &/ CGI["SCRIPT_NAME"] &/ CGI["PATH_INFO"]
  IF CGI["QUERY_STRING"] THEN sReq &= "?" & CGI["QUERY_STRING"]
  RETURN sReq
  
END

PRIVATE FUNCTION Root_Read() AS String

  RETURN CGI["SCRIPT_NAME"]

END


PRIVATE FUNCTION LogFile_Read() AS String

  RETURN $sLogFile

END

PRIVATE SUB LogFile_Write(Value AS String)

  IF $sLogFile THEN ERROR TO DEFAULT

  $sLogFile = Value
  $hLogFile = OPEN $sLogFile FOR APPEND 
  ERROR TO #$hLogFile
  
END

PRIVATE FUNCTION Protocol_Read() AS String

  RETURN $sProtocol  

END

PRIVATE SUB Protocol_Write(Value AS String)

  $sProtocol = Value

END
