' Gambas module file

EXPORT 

' PRIVATE SUB Quote(sStr AS String) AS String
'   
'   RETURN Replace(sStr, "\"", "\"\"")
'   
' END
' 
' PRIVATE SUB UnQuote(sStr AS String) AS String
'   
'   RETURN Replace(sStr, "\"\"", "\"")
'   
' END


PUBLIC SUB _GetColumnViewSettings(hColumnView AS ColumnView) AS String
  
  DIM sVal AS String
  DIM iCol AS Integer

  WITH hColumnView

    sVal = CStr(.Columns.Count)
    
    FOR iCol = 0 TO .Columns.Count - 1
      'sVal &= "," & "\"" & Quote(.Columns[iCol].Text) & "\""
      sVal &= "," & CStr(Round(.Columns[iCol].Width / Desktop.Scale, -3))
      SELECT CASE .Columns[iCol].Alignment 
        CASE Align.Left
          sVal &= ",<"
        CASE Align.Right
          sVal &= ",>"
      END SELECT
      IF .Columns.Sort = iCol THEN 
        IF .Columns.Ascending THEN 
          sVal &= ",+"
        ELSE 
          sVal &= ",-"
        ENDIF
      ENDIF
    NEXT    
  
  END WITH 
  
  'DEBUG sVal
  
  RETURN sVal
  
END

PUBLIC SUB _SetColumnViewSettings(hColumnView AS ColumnView, sSettings AS String)

  DIM aVal AS String[]
  DIM iInd AS Integer
  DIM iCol AS Integer
  DIM eWidth AS Float[]
  DIM eSum AS Float

  'DEBUG sSettings

  aVal = Split(sSettings, ",", "\"")
  
  WITH hColumnView

    .Columns.Count = CInt(aVal[0])
    eWidth = NEW Float[.Columns.Count]
    INC iInd
    WHILE iCol < .Columns.Count
      IF iInd >= aVal.Count THEN BREAK 
      'DEBUG iCol;; "=";; CFloat(aVal[iInd])
      eWidth[iCol] = CFloat(aVal[iInd]) * Desktop.Scale
      eSum += eWidth[iCol]
      INC iInd
      DO
        IF iInd >= aVal.Count THEN BREAK 
        SELECT CASE aVal[iInd] 
          CASE "<"
            .Columns[iCol].Alignment = Align.Left
          CASE ">"
            .Columns[iCol].Alignment = Align.Right
          CASE "+"
            .Columns.Sort = iCol
            .Columns.Ascending = TRUE
          CASE "-"
            .Columns.Sort = iCol
            .Columns.Ascending = FALSE
          CASE ELSE 
            BREAK 
        END SELECT 
        INC iInd
      LOOP
      INC iCol
    WEND
    
    iCol = 0
    WHILE iInd < aVal.Count AND iCol < .Columns.Count
      .Columns[iCol].Text = UnQuote(aVal[iInd])
      INC iCol
      INC iInd      
    WEND
    
    IF eSum > 0 THEN
      FOR iCol = 0 TO .Columns.Count - 1
        .Columns[iCol].Width = eWidth[iCol] * .ClientW / eSum
      NEXT
      ' ELSE
      '   FOR iCol = 0 TO .Columns.Count - 1
      '     .Columns[iCol].Width = eWidth[iCol]
      '     'DEBUG iCol;; ":";; .Columns[iCol].Width / Desktop.Scale
      '   NEXT
    ENDIF
    
    'DEBUG sSettings;; "->";; hColumnView.Settings
  
  END WITH
  
CATCH 

  DEBUG Error.Where; ": "; Error.Text

END

