' Gambas module file

PRIVATE $cIconMap AS NEW Collection

PRIVATE SUB LoadMap(sMap AS String)
  
  DIM hFile AS File
  DIM sLig AS String
  DIM aMap AS String[]
  DIM cMap AS NEW Collection

  IF $cIconMap.Exist(sMap) THEN RETURN

  hFile = OPEN "map" &/ sMap & ".map"
  WHILE NOT Eof(hFile)
    LINE INPUT #hFile, sLig
    sLig = Trim(sLig)
    IF Left(sLig) = "'" OR Left(sLig) = "#" THEN CONTINUE
    aMap = Scan(sLig, "* *")
    IF aMap.Count >= 2 THEN
      cMap[aMap[0]] = aMap[1]
    ENDIF
  WEND
  CLOSE #hFile
  
  $cIconMap[sMap] = cMap
    
END


SUB Main()
  
  DIM sPath AS String
  DIM cMap AS Collection
  DIM sSize AS String
  DIM sSrc AS String
  DIM sDest AS String
  DIM sRoot AS String
  
  sRoot = "/home/benoit/gambas/2.0/trunk/gb.qt/src/gb.qt"
  
  TRY MKDIR sRoot &/ "default"
  
  LoadMap("kde")
  cMap = $cIconMap["kde"]
  
  FOR EACH sSize IN ["16", "32", "48", "64"]
    TRY MKDIR sRoot &/ "default" &/ sSize
    FOR EACH sPath IN cMap
      PRINT cMap.Key
      sSrc = "/usr/share/icons/crystalsvg/" & sSize & "x" & sSize &/ sPath
      IF NOT Exist(sSrc) THEN CONTINUE
      sDest = sRoot &/ "default" &/ sSize &/ cMap.Key & ".png"
      TRY KILL sDest
      COPY sSrc TO sDest
    NEXT
  NEXT
  
END
