' Gambas module file

PUBLIC SUB Main()

  ' DIM eTime AS Date
  ' 
  ' eTime = Timer
  ' Info["gb"].Load
  ' Info["gb.eval"].Load
  ' Info["gb.debug"].Load
  ' Info["gb.db"].Load
  ' Info["gb.qt"].Load
  ' Info["gb.qt.ext"].Load
  ' Info["gb.form"].Load
  ' Info["gb.info"].Load
  ' Info["gb.report"].Load
  ' PRINT Timer - eTime

  'Make

  'PRINT Info.Components.Join("\n")

  Info["gb.qte"].Load

END


