' Gambas module file

Public Sub Main()

  Dim hWIn As New Window
  Dim hLab1 As New Label(hWin)
  
  Dim hC As Control
  Dim Lab2 As Label
  ' 
  hWIn.Tag = "Win"
  hWin.Left = 10
  hWIn.Top = 2
  hWIn.Height = 15
  hWIn.Width = 50
  hWIn.Background = Color.red
  hWin.Title = "My First Window"
  hLab1.Left = 4
  hLab1.Top = 2
  hLab1.Width = 10
  hLab1.Height = 1
  hLab1.Text = "Label 1"
  hLab1.Tag = 1
  
  
  hWin = New Window
  hWin.Width = 50
  hWIn.Height = 15
  hWIn.Top = 7
  hWin.Left = 20
  hWIn.Title = "My Second Window"
  Lab2 = New Label(hWin)
  Lab2.Height = 1
  Lab2.Width = 35
  Lab2.Left = 4
  Lab2.Top = 2
  Lab2.Background = Color.Green
  Lab2.Foreground = Color.Red
  Lab2.Text = "Another Label On Another Form"

  Windows.Render


End
