# Gambas Action File 3.0

{ Actions
  { Action align-bottom
    Text = "Align to bottom"
    Shortcut = ""
    Picture = "img/16/align-bottom.png"
  }
  { Action align-left
    Text = "Align to left"
    Shortcut = ""
    Picture = "img/16/align-left.png"
  }
  { Action align-right
    Text = "Align to right"
    Shortcut = ""
    Picture = "img/16/align-right.png"
  }
  { Action align-top
    Text = "Align to top"
    Shortcut = ""
    Picture = "img/16/align-top.png"
  }
  { Action arrange-column
    Text = "Columns"
    Shortcut = ""
    Picture = "img/16/arrange-tb.png"
  }
  { Action arrange-hcenter
    Text = "Center horizontally"
    Shortcut = ""
    Picture = "img/16/arrange-hcenter.png"
  }
  { Action arrange-horizontal
    Text = "Horizontal"
    Shortcut = "Ctrl+Alt+H"
    Picture = "img/16/arrange-h.png"
  }
  { Action arrange-row
    Text = "Rows"
    Shortcut = ""
    Picture = "img/16/arrange-lr.png"
  }
  { Action arrange-vcenter
    Text = "Center vertically"
    Shortcut = ""
    Picture = "img/16/arrange-vcenter.png"
  }
  { Action arrange-vertical
    Text = "Vertical"
    Shortcut = "Ctrl+Alt+V"
    Picture = "img/16/arrange-v.png"
  }
  { Action close
    Text = "Close"
    Shortcut = "Ctrl+W"
    Picture = "icon:/small/close"
  }
  { Action code-form
    Text = "Open code"
    Shortcut = "F12"
    Picture = "img/16/class.png"
  }
  { Action copy
    Text = "Copy"
    Shortcut = "Ctrl+C"
    Picture = "icon:/small/copy"
  }
  { Action copy-same
    Text = "Copy at the same place"
    Shortcut = "Ctrl+Shift+C"
  }
  { Action cut
    Text = "Cut"
    Shortcut = "Ctrl+X"
    Picture = "icon:/small/cut"
  }
  { Action delete
    Text = "Delete"
    Shortcut = "Del"
    Picture = "icon:/small/delete"
  }
  { Action delete-container
    Text = "Delete container only"
    Shortcut = ""
    Picture = "img/16/delete-container.png"
  }
  { Action embed-container
    Text = "Embed into a container"
    Shortcut = ""
    Picture = "img/16/embed-container.png"
  }
  { Action format-background
    Text = "Background"
    Picture = "icon:/small/fill"
  }
  { Action format-foreground
    Text = "Foreground"
    Picture = "icon:/small/pen"
  }
  { Action grid
    Text = "Toggle grid"
    Picture = "icon:/small/grid"
  }
  { Action locked
    Text = "Locked"
    Shortcut = ""
    Picture = "icon:/small/lock"
  }
  { Action lower
    Text = "Send to background"
    Shortcut = "End"
    Picture = "img/16/lower.png"
  }
  { Action menu
    Text = "Menu editor"
    Shortcut = "Ctrl+E"
    Picture = "icon:/small/menu"
  }
  { Action move-tab-first
    Text = "First"
    Shortcut = "Ctrl+Alt+Home"
    Picture = "icon:/small/first"
  }
  { Action move-tab-last
    Text = "Last"
    Shortcut = "Ctrl+Alt+End"
    Picture = "icon:/small/last"
  }
  { Action move-tab-next
    Text = "Next"
    Shortcut = "Ctrl+Alt+Right"
    Picture = "icon:/small/right"
  }
  { Action move-tab-previous
    Text = "Previous"
    Shortcut = "Ctrl+Alt+Left"
    Picture = "icon:/small/left"
  }
  { Action paste
    Text = "Paste"
    Shortcut = "Ctrl+V"
    Picture = "icon:/small/paste"
  }
  { Action raise
    Text = "Bring to foreground"
    Shortcut = "Home"
    Picture = "img/16/raise.png"
  }
  { Action redo
    Text = "Redo"
    Shortcut = "Ctrl+Y"
    Picture = "icon:/small/redo"
  }
  { Action reload
    Text = "Reload"
    Shortcut = ""
    Picture = "icon:/small/revert"
  }
  { Action run-me
    Text = "Run this form"
    Shortcut = "Shift+F5"
    Picture = "icon:/small/play"
  }
  { Action same-height
    Text = "Same height"
    Shortcut = ""
    Picture = "img/16/same-height.png"
  }
  { Action same-width
    Text = "Same width"
    Shortcut = ""
    Picture = "img/16/same-width.png"
  }
  { Action save
    Text = "Save"
    Shortcut = "Ctrl+S"
    Picture = "icon:/small/save"
  }
  { Action select-all
    Text = "Select all"
    Shortcut = "Ctrl+A"
  }
  { Action select-parent
    Text = "Select parent"
    Shortcut = ""
  }
  { Action show-class
    Text = "Code"
    Picture = "icon:/small/next"
  }
  { Action show-tab
    Text = "Show tab"
    Picture = "img/16/tabstrip.png"
  }
  { Action text-bold
    Text = "Bold"
    Picture = "icon:/small/text-bold"
  }
  { Action text-font
    Text = ""
    Picture = "icon:/small/font"
  }
  { Action text-italic
    Text = "Italic"
    Picture = "icon:/small/text-italic"
  }
  { Action text-underline
    Text = "Underline"
    Picture = "icon:/small/text-underline"
  }
  { Action text-zoom-in
    Text = "Bigger font"
    Picture = "icon:/small/zoom-in"
  }
  { Action text-zoom-normal
    Text = "Default font"
    Picture = "icon:/small/zoom-normal"
  }
  { Action text-zoom-out
    Text = "Smaller font"
    Picture = "icon:/small/zoom-out"
  }
  { Action undo
    Text = "Undo"
    Shortcut = "Ctrl+Z"
    Picture = "icon:/small/undo"
  }
  { Action unselect-all
    Text = "Unselect all"
    Shortcut = "Esc"
  }
}

{ Toolbars
  { Toolbar form
    Text = "Form"
    List = "show-class,save,reload,locked,run-me,cut,copy,paste,delete,undo,redo,menu,grid,raise,lower,align-top,align-bottom,align-left,align-right,same-width,same-height,arrange-vertical,arrange-horizontal,arrange-column,arrange-row,arrange-hcenter,arrange-vcenter,move-tab-first,move-tab-previous,move-tab-next,move-tab-last,show-tab,text-font,text-bold,text-italic,text-underline,text-zoom-in,text-zoom-out,text-zoom-normal,format-background,format-foreground"
    Default = "show-class,save,reload,locked,undo,redo,menu,grid,|,raise,lower,align-top,align-bottom,align-left,align-right,same-width,same-height,arrange-hcenter,arrange-vcenter,|,move-tab-first,move-tab-previous,move-tab-next,move-tab-last,show-tab,|,text-font,text-bold,text-italic,text-underline,text-zoom-in,text-zoom-out,text-zoom-normal,format-background,format-foreground"
  }
}

