# Gambas Action File 3.0

{ Actions
  { Action _close
    Text = "Close"
    Shortcut = "Ctrl+W"
    Picture = "icon:/small/close"
  }
  { Action _reload
    Text = "Reload"
    Shortcut = ""
    Picture = "icon:/small/revert"
  }
  { Action _save
    Text = "Save"
    Shortcut = ""
    Picture = "icon:/small/save"
  }
  { Action about
    Text = "About Gambas"
    Shortcut = ""
    Picture = "icon:/small/info"
  }
  { Action archive
    Text = "Source archive"
    Shortcut = "Ctrl+Alt+A"
    Picture = "icon:/small/archive"
  }
  { Action browse-project
    Text = "Browse project"
    Shortcut = "Ctrl+Alt+O"
    Picture = "icon:/small/file-manager"
  }
  { Action clean-up-project
    Text = "Clean up"
    Shortcut = ""
    Picture = "icon:/small/clear"
  }
  { Action clear-break
    Text = "Clear all breakpoints"
    Shortcut = ""
  }
  { Action close-all-debug
    Text = "Close all debug windows"
    Shortcut = ""
  }
  { Action close-all-window
    Text = "Close all windows"
    Shortcut = "Ctrl+Alt+W"
  }
  { Action compile
    Text = "Compile"
    Shortcut = "F7"
    Picture = "icon:/small/make"
  }
  { Action compile-all
    Text = "Compile All"
    Shortcut = "Alt+F7"
    Picture = "icon:/small/make-all"
  }
  { Action compress-all
    Text = "Compress all"
    Shortcut = ""
    Picture = "icon:/small/archive"
  }
  { Action console
    Text = "Console"
    Shortcut = "F11"
    Picture = "icon:/small/terminal"
  }
  { Action control
    Text = "Toolbox"
    Picture = "icon:/small/tools"
  }
  { Action copy
    Text = "Copy"
    Shortcut = "Ctrl+C"
    Picture = "icon:/small/copy"
  }
  { Action copy-file-path
    Text = "Copy file path"
    Shortcut = "Ctrl+Shift+C"
  }
  { Action cut
    Text = "Cut"
    Shortcut = "Ctrl+X"
    Picture = "icon:/small/cut"
  }
  { Action delete
    Text = "Delete"
    Shortcut = "Del"
    Picture = "icon:/small/delete"
  }
  { Action exec
    Text = "Executable"
    Shortcut = "Ctrl+Alt+X"
    Picture = "icon:/small/exec"
  }
  { Action farm
    Text = "Software farm"
    Shortcut = ""
    Picture = "icon:/small/book"
  }
  { Action find
    Text = "Search"
    Picture = "icon:/small/find"
  }
  { Action find-project
    Text = "Browse project..."
    Picture = "icon:/small/find"
  }
  { Action forward
    Text = "Forward"
    Shortcut = "Shift+F8"
    Picture = "icon:/small/forward"
  }
  { Action go-back
    Text = "Go back"
    Shortcut = "Alt+Left"
    Picture = "icon:/small/left"
  }
  { Action go-forward
    Text = "Go forward"
    Shortcut = "Alt+Right"
    Picture = "icon:/small/right"
  }
  { Action gui
    Text = "GUI component"
    Shortcut = ""
    Picture = "icon:/small/desktop"
  }
  { Action help
    Text = "Help browser"
    Shortcut = "F1"
    Picture = "icon:/small/help"
  }
  { Action help-shortcut
    Text = "Keyboard shortcuts"
    Shortcut = ""
    Picture = "icon:/small/shortcut"
  }
  { Action httpserver
    Text = "Use embedded HTTP server"
    Shortcut = ""
  }
  { Action info
    Text = "Properties"
    Shortcut = "Ctrl+I"
    Picture = "icon:/small/info"
  }
  { Action install
    Text = "Installation package"
    Shortcut = "Ctrl+Alt+I"
    Picture = "icon:/small/package"
  }
  { Action menu-debug
    Text = "Debug"
    Picture = "$MenuButton"
  }
  { Action menu-edit
    Text = "Edit"
    Picture = "$MenuButton"
  }
  { Action menu-file
    Text = "File"
    Picture = "$MenuButton"
  }
  { Action menu-help
    Text = "?"
    Picture = "$MenuButton"
  }
  { Action menu-project
    Text = "Project"
    Picture = "$MenuButton"
  }
  { Action menu-tool
    Text = "Tools"
    Picture = "$MenuButton"
  }
  { Action menu-view
    Text = "View"
    Picture = "$MenuButton"
  }
  { Action new-other
    Text = "Other"
    Shortcut = ""
    Picture = "icon:/small/new"
  }
  { Action new-project
    Text = "New project"
    Shortcut = "Ctrl+N"
    Picture = "icon:/small/new"
  }
  { Action open-extern
    Text = "Open"
    Shortcut = "Ctrl+O"
    Picture = "icon:/small/open"
  }
  { Action open-file-manager
    Text = "Open in file manager"
    Shortcut = ""
    Picture = "icon:/small/file-manager"
  }
  { Action open-profile
    Text = "Open profile"
    Shortcut = ""
    Picture = "icon:/small/clock"
  }
  { Action open-project
    Text = "Open project"
    Shortcut = "Ctrl+O"
    Picture = "icon:/small/open"
  }
  { Action open-terminal
    Text = "Open a terminal"
    Shortcut = "Ctrl+Alt+T"
    Picture = "icon:/small/terminal"
  }
  { Action option
    Text = "Preferences"
    Shortcut = "Ctrl+Alt+P"
    Picture = "icon:/small/options"
  }
  { Action paste
    Text = "Paste"
    Shortcut = "Ctrl+V"
    Picture = "icon:/small/paste"
  }
  { Action pause
    Text = "Pause"
    Shortcut = "Pause"
    Picture = "icon:/small/pause"
  }
  { Action profile
    Text = "Activate profiling"
    Shortcut = ""
  }
  { Action project
    Text = "Project"
    Shortcut = "F10"
    Picture = "icon:/small/view-split-h"
  }
  { Action project-property
    Text = "Properties"
    Shortcut = "Ctrl+P"
    Picture = "icon:/small/edit"
  }
  { Action project-version
    Text = "Version control"
    Shortcut = ""
    Picture = "icon:/small/calendar"
  }
  { Action property
    Text = "Properties"
    Shortcut = "F4"
    Picture = "icon:/small/edit"
  }
  { Action publish
    Text = "Publish"
    Shortcut = ""
    Picture = "icon:/small/internet"
  }
  { Action quit
    Text = "Quit"
    Shortcut = "Ctrl+Q"
    Picture = "icon:/small/quit"
  }
  { Action redirect
    Text = "Redirect standard error output"
    Shortcut = ""
  }
  { Action refresh-project
    Text = "Refresh"
    Shortcut = ""
    Picture = "icon:/small/refresh"
  }
  { Action rename
    Text = "Rename"
    Shortcut = "F2"
    Picture = "img/16/rename.png"
  }
  { Action return
    Text = "Finish"
    Shortcut = ""
    Picture = "icon:/small/eject"
  }
  { Action run-that
    Text = "Run this class"
    Shortcut = ""
    Picture = "icon:/small/play"
  }
  { Action save-as
    Text = "Save as"
    Shortcut = "Ctrl+Alt+S"
    Picture = "icon:/small/save-as"
  }
  { Action save-project
    Text = "Save project"
    Shortcut = "Ctrl+Alt+S"
    Picture = "icon:/small/save"
  }
  { Action save-project-as
    Text = "Save project as"
    Shortcut = "Ctrl+Shift+Alt+S"
    Picture = "icon:/small/save-as"
  }
  { Action send-mail
    Text = "Send project by mail"
    Shortcut = ""
    Picture = "icon:/small/mail"
  }
  { Action shortcut
    Text = "Shortcuts"
    Shortcut = ""
    Picture = "icon:/small/shortcut"
  }
  { Action start
    Text = "Run"
    Shortcut = "F5"
    Picture = "icon:/small/play"
  }
  { Action startup-class
    Text = "Startup class"
    Shortcut = "Alt+S"
    Picture = "img/16/startup-class.png"
  }
  { Action step
    Text = "Step"
    Shortcut = "F8"
    Picture = "icon:/small/end"
  }
  { Action stop
    Text = "Stop"
    Shortcut = "Alt+Pause"
    Picture = "icon:/small/stop"
  }
  { Action terminal
    Text = "Use terminal emulator"
    Shortcut = ""
  }
  { Action tips
    Text = "Tips of the day"
    Shortcut = ""
    Picture = "icon:/small/lamp"
  }
  { Action translate
    Text = "Translate"
    Shortcut = "Ctrl+T"
    Picture = "icon:/small/language"
  }
  { Action uncompress-all
    Text = "Uncompress all"
    Shortcut = ""
    Picture = "icon:/small/undo"
  }
  { Action until
    Text = "Run until current line"
    Picture = "icon:/small/jump"
  }
  { Action update-all-forms
    Text = "Update all forms"
    Shortcut = ""
    Picture = "icon:/small/refresh"
  }
  { Action version-control
    Text = "Put on version control"
    Shortcut = ""
    Picture = "icon:/small/add"
  }
}

{ Toolbars
  { Toolbar main
    Text = ""
    List = "new-project,open-project,save-project,save-project-as,project-property,project-version,refresh-project,option,shortcut,exec,translate,archive,install,project,property,control,console,find,help,compile,compile-all,start,pause,stop,step,forward,return,until,find-project,go-back,go-forward,browse-project,open-terminal,send-mail,publish,farm,gui,menu-file,menu-edit,menu-project,menu-debug,menu-view,menu-tool,menu-help"
    Default = "new-project,open-project,save-project,save-project-as,project-property,project-version,option,|,exec,translate,|,compile,compile-all,start,pause,stop,step,forward,return,until,-,find-project,go-back,go-forward"
  }
}

