include(GNUInstallDirs)
# Gambas Extra CMake Modules
set(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/config/modules/" ${CMAKE_MODULE_PATH})


# Gambas Version Information

set(GAMBAS_VERSION_MAJOR 3)
set(GAMBAS_VERSION_MINOR 10)
set(GAMBAS_VERSION_REVISON 90)

# Gambas Source Configuration

set(GAMBAS_SOURCE_INCLUDE_DIR "${GAMBAS_SOURCE_ROOT}/include" "${GAMBAS_SOURCE_ROOT}/main/common")
set(GAMBAS_SOURCE_CONFIG_DIR "${GAMBAS_SOURCE_ROOT}/config")
set(GAMBAS_SOURCE_CONFIG_FILE "${GAMBAS_SOURCE_CONFIG_DIR}/config.h")
set(GAMBAS_SOURCE_OUTPUT_DIR "${GAMBAS_SOURCE_ROOT}/build")
set(GAMBAS_SOURCE_BINARY_DIR "${GAMBAS_SOURCE_OUTPUT_DIR}/bin")
set(GAMBAS_SOURCE_LIBRARY_DIR "${GAMBAS_SOURCE_OUTPUT_DIR}/lib/gambas${GAMBAS_VERSION_MAJOR}")
set(GAMBAS_SOURCE_INFO_DIR "${GAMBAS_SOURCE_OUTPUT_DIR}/share/gambas${GAMBAS_VERSION_MAJOR}/info")

#CMake Configuration
#set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${GAMBAS_SOURCE_LIBRARY_DIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${GAMBAS_SOURCE_LIBRARY_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${GAMBAS_SOURCE_BINARY_DIR})

include("${CMAKE_SOURCE_DIR}/config/config.cmake")
include(GambasComponent)
