# Gambas Action File 3.0

{ Actions
  { Action About
    Text = "About"
    Shortcut = "Alt+A"
    Picture = "icons/16/About.png"
  }
  { Action Backup
    Text = "Backup"
    Shortcut = "Alt+B"
    Picture = "icons/16/Backup.png"
  }
  { Action Catalogs
    Text = "Catalogs"
    Shortcut = "Alt+C"
    Picture = "icons/16/Catalogs.png"
  }
  { Action CloseAllForms
    Text = "Close all forms"
    Shortcut = "Ctrl+Alt+Esc"
    Picture = "icon:/16/close"
  }
  { Action Closeform
    Text = "Close form"
    Shortcut = "Alt+Esc"
    Picture = "icon:/16/close"
  }
  { Action Help
    Text = "Help"
    Shortcut = "F1"
    Picture = "icon:/16/help"
  }
  { Action Hidepanels
    Text = "Hide panels"
    Shortcut = "F8"
    Picture = "icon:/16/view-split-h"
  }
  { Action Preferences
    Text = "Preferences"
    Shortcut = "Alt+P"
    Picture = "icon:/16/options"
  }
  { Action Query
    Text = "Query"
    Shortcut = "Alt+Q"
    Picture = "icons/16/Query.png"
  }
  { Action Restore
    Text = "Restore Backup"
    Shortcut = "Alt+R"
    Picture = "icons/16/Restore.png"
  }
  { Action Script
    Text = "Script"
    Shortcut = "Alt+S"
    Picture = "icons/16/Script2.png"
  }
  { Action Server
    Text = "Server Information"
    Shortcut = "Alt+I"
    Picture = "icons/16/Server.png"
  }
  { Action Users
    Text = "User Administration"
    Shortcut = "Alt+U"
    Picture = "icons/16/UserAdmin.png"
  }
}

