' Gambas module file

Private $cArrow As New Collection

Public Sub GetArrow(iType As Integer, iSize As Integer) As Image
  
  Dim sKey As String
  Dim hPict As Picture
  Dim hImage As Image
  
  Select Case iType
    Case Align.Top
      sKey = "top"
    Case Align.Bottom
      sKey = "bottom"
    Case Align.Left
      sKey = "left"
    Case Align.Right
      sKey = "right"
  End Select

  sKey = sKey & "-" & iSize

  hImage = $cArrow[sKey]
  If Not hImage Then 
    hPict = New Picture(16, 16)
    hPict.Fill(Color.White)
    Draw.Begin(hPict)
    Draw.Style.Arrow(0, 0, 16, 16, iType)
    Draw.End
    hImage = hPict.Image.Stretch(iSize, iSize)
    hImage.Erase()
    'hPict = hImage.Picture
    $cArrow[sKey] = hImage
  Endif
  Return hImage
  
End

Public Sub Main()
  
  Message.Optional("<h2>Votre document n'a pas été enregistré.</h2>\nVous risquez de perdre votre travail !<p>C'est grave, très grave même !<p>Veuillez faire attention à ce que vous allez faire et n'agissez qu'avec la plus entière circonception.</p>", "OK",, "Test")
  
End
