' Gambas module file

Export 

' PRIVATE SUB Quote(sStr AS String) AS String
'   
'   RETURN Replace(sStr, "\"", "\"\"")
'   
' END
' 
' PRIVATE SUB UnQuote(sStr AS String) AS String
'   
'   RETURN Replace(sStr, "\"\"", "\"")
'   
' END


Public Sub _GetColumnViewSettings(hColumnView As ColumnView) As String
  
  Dim sVal As String
  Dim iCol As Integer

  With hColumnView

    sVal = CStr(.Columns.Count)
    
    For iCol = 0 To .Columns.Count - 1
      'sVal &= "," & "\"" & Quote(.Columns[iCol].Text) & "\""
      sVal &= "," & CStr(Round(.Columns[iCol].Width / Desktop.Scale, -3))
      Select Case .Columns[iCol].Alignment 
        Case Align.Left
          sVal &= ",<"
        Case Align.Right
          sVal &= ",>"
      End Select
      If .Columns.Sort = iCol Then 
        If .Columns.Ascending Then 
          sVal &= ",+"
        Else 
          sVal &= ",-"
        Endif
      Endif
    Next    
  
  End With 
  
  Return sVal
  
End

Public Sub _SetColumnViewSettings(hColumnView As ColumnView, sSettings As String)

  Dim aVal As String[]
  Dim iInd As Integer
  Dim iCol As Integer
  Dim eWidth As Float[]
  Dim eSum As Float

  aVal = Split(sSettings, ",", "\"")
  
  With hColumnView

    .Columns.Count = CInt(aVal[0])
    eWidth = New Float[.Columns.Count]
    Inc iInd
    While iCol < .Columns.Count
      If iInd >= aVal.Count Then Break 
      'DEBUG iCol;; "=";; CFloat(aVal[iInd])
      eWidth[iCol] = CFloat(aVal[iInd]) * Desktop.Scale
      eSum += eWidth[iCol]
      Inc iInd
      Do
        If iInd >= aVal.Count Then Break 
        Select Case aVal[iInd] 
          Case "<"
            .Columns[iCol].Alignment = Align.Left
          Case ">"
            .Columns[iCol].Alignment = Align.Right
          Case "+"
            .Columns.Sort = iCol
            .Columns.Ascending = True
          Case "-"
            .Columns.Sort = iCol
            .Columns.Ascending = False
          Case Else 
            Break 
        End Select 
        Inc iInd
      Loop
      Inc iCol
    Wend
    
    iCol = 0
    While iInd < aVal.Count And iCol < .Columns.Count
      .Columns[iCol].Text = Unquote(aVal[iInd])
      Inc iCol
      Inc iInd      
    Wend
    
    If eSum > 0 Then
      For iCol = 0 To .Columns.Count - 1
        .Columns[iCol].Width = eWidth[iCol] * .ClientW / eSum
      Next
      ' ELSE
      '   FOR iCol = 0 TO .Columns.Count - 1
      '     .Columns[iCol].Width = eWidth[iCol]
      '     'DEBUG iCol;; ":";; .Columns[iCol].Width / Desktop.Scale
      '   NEXT
    Endif
    
    'DEBUG sSettings;; "->";; hColumnView.Settings
  
  End With
  
Catch 

  Debug Error.Where; ": "; Error.Text

End

