' Gambas module file

Public PageCount As Integer = 0
Public ResolutionAffichage As Float '= 72
'Public ReportZoom As Float '= 1
Public ReportResolution As Float '= 72

Private Dash As Float[] = [2.0, 1.0]
Private Dot As Float[] = [1.0, 1.0]
Private DashDot As Float[] = [2.0, 1.0, 1.0, 1.0]
Private DashDotDot As Float[] = [2.0, 1.0, 1.0, 1.0, 1.0, 1.0]

Public Function UnitsToPixels(Value As Float) As Integer
  
  Dim f As Float
  
  f = Units.GetFactorUnitToInch("cm") * ReportResolution
  
  Return Value * f 
End

Public Function PixelsToUnits(Value As Integer) As Float
  Dim f As Float
  
  f = Units.GetFactorUnitToInch("cm") * ReportResolution
    
  Return (Value) / f
End
Public Function ScanValue(sText As String) As TSizeParse
  
  Dim i As Integer
  Dim s As String
  Dim sVal As String 
  Dim sUnit As String
  Dim hTSP As New TSizeParse
  If Not sText Then sText = "0 px"
  
  For i = 1 To Len(sText)
    s = Mid(sText, i, 1)
    If IsDigit(s) Or s = "." Then 
      sVal &= s
      Continue
    Endif 
    If IsLetter(s) Or s = "%" Then 
      sUnit &= s
    Endif
  Next 
  
  hTSP.Value = CFloat(Trim(sVal))

  hTsp.Unit = sUnit
  Return hTSP
  
  End

Public Sub GetBorder(iStyle As Integer) As Float[]
  
  Select Case iStyle
  
    Case ReportBorder.Dash
      Return Dash
    Case ReportBorder.Dot
      Return Dot
    Case ReportBorder.DashDot
      Return DashDot
    Case ReportBorder.DashDotDot
      Return DashDotDot
  End Select
  
End

