' Gambas module file

Public PageCount As Integer = 0
'Public ReportZoom As Float '= 1
Public ReportResolution As Float '= 72

Public DrawCount As Integer

Private Dash As Float[] = [2.0, 1.0]
Private Dot As Float[] = [1.0, 1.0]
Private DashDot As Float[] = [2.0, 1.0, 1.0, 1.0]
Private DashDotDot As Float[] = [2.0, 1.0, 1.0, 1.0, 1.0, 1.0]

Public Function UnitsToPixels(Value As Float) As Integer
  
  Dim f As Float
  
  f = Units.GetFactorUnitToInch("cm") * ReportResolution
  
  Return Value * f 
End

Public Function PixelsToUnits(Value As Integer) As Float
  Dim f As Float
  
  f = Units.GetFactorUnitToInch("cm") * ReportResolution
    
  Return (Value) / f
End
Public Function ScanValue(sText As String) As TSizeParse
  
  Dim i As Integer
  Dim s As String
  Dim sVal As String 
  Dim sUnit As String
  Dim hTSP As New TSizeParse
  If Not sText Then sText = "0 px"
  
  For i = 1 To Len(sText)
    s = Mid(sText, i, 1)
    If IsDigit(s) Or s = "." Then 
      sVal &= s
      Continue
    Endif 
    If IsLetter(s) Or s = "%" Then 
      sUnit &= s
    Endif
  Next 
  
  hTSP.Value = CFloat(Trim(sVal))

  hTsp.Unit = sUnit
  Return hTSP
  
  End

Public Sub GetBorder(iStyle As Integer) As Float[]
  
  Select Case iStyle
  
    Case Line.Dash
      Return Dash
    Case Line.Dot
      Return Dot
    Case Line.DashDot
      Return DashDot
    Case Line.DashDotDot
      Return DashDotDot
  End Select
  
End

' Public Sub ToAlignment(iAlignment As Integer) As Integer
'   
'   Select Case iAlignment
'     Case ReportAlign.Normal
'       Return Align.Normal
'     Case ReportAlign.Left
'       Return Align.Left
'     Case ReportAlign.Right
'       Return Align.Right
'     Case ReportAlign.Center
'       Return Align.Center
'     Case ReportAlign.Normal
'       Return Align.Normal
'     Case ReportAlign.TopLeft
'       Return Align.TopLeft
'     Case ReportAlign.TopRight
'       Return Align.TopRight
'     Case ReportAlign.TopCenter
'       Return Align.TopCenter
'     Case ReportAlign.BottomNormal
'       Return Align.BottomNormal
'     Case ReportAlign.BottomLeft
'       Return Align.BottomLeft
'     Case ReportAlign.BottomRight
'       Return Align.BottomRight
'     Case ReportAlign.BottomCenter
'       Return Align.BottomCenter
'   End Select
'   
' End
