# Gambas Action File 3.0

{ Actions
  { Action NewTab
    Text = "New Script"
    Shortcut = "Ctrl+N"
    Picture = "icons/16/ScriptTab.png"
  }
  { Action Run
    Text = "Run script"
    Shortcut = "Ctrl+Return"
    Picture = "icons/16/Script2.png"
  }
}

