######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 4 21:47:56 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . /usr/include/c++/4.6.1

# Input
HEADERS += CDocument.h CElement.h \
    hdocument.h \
    helement.h \
    main.h
SOURCES += CDocument.cpp CElement.cpp \
    hdocument.cpp \
    helement.cpp \
    main.cpp
