' Gambas module file

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 2 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

Public Sub Main()

  Dim POP As New Pop3Client

  Dim i As Variant

  Dim a As Variant

  POP.Encrypt = Net.None

  POP.Username = "USER"
  POP.Password = "PASSWORD"

  POP.Server = "pop3.SERVER.com"

  POP.Open()

  'POP.WaitForConnection()

  'i = POP.Stat()

  'POP.NOOP()

  ' Print POP.Size, POP.Count

  'Print POP.Size, POP.Count

  'a = POP.List()
  ' POP.List(4)
  '
  '
  ' Wait 3
  '
  'i = POP[4]

  a = POP[4].Size
  i = POP[4].UniqueID
  '
  ' i = POP.UniqueID(4)

  'a = POP.UniqueID()

  Stop
  '
  ' POP.List()
  '
  'Wait
  'Print POP.Retrieve(4)

  'POP.NOOP()

  For i = 1 To 10
    '
    a = POP.List()
    'Print POP.Send("NOOP")

    'Wait 0.1
  Next

  'Wait 2

  POP.Quit()

  POP.Disconnect()

  ' Stop

End
