' Gambas module file

Public ColorList As Integer[] = [&hff6f00,
&h800080, &h666666, &h6B4794, &h290099, &h7da647,
&he6e64c, &hff9966, &h000080, &hfff0ff, &h00ffff, &h9999ff]

Public Function GetChartMaxValue(oChart As Chart) As Float
  Dim hSeries As _CSerie
  Dim f As Float
  Dim fCurMax As Float
  fCurMax = 0
  For Each hSeries In oChart
    For Each f In hSeries
      If fCurMax < f Then fCurMax = f
    Next
  Next
  Return fCurMax
  
End

Public Function GetChartMaxCumulateValue(oChart As Chart) As Float
  Dim hSeries As _CSerie
  Dim f As Float
  Dim fCurMax As Float
  Dim i As Integer
  fCurMax = 0
  For i = 0 To oChart.Count - 1
    f = 0
    For Each hSeries In Chart
      f += hSeries[i]
    Next
    If fCurMax < f Then fCurMax = f
  Next
  Return fCurMax
End

Public Function GetChartMaxCumulate(oChart As Chart) As Float
  
  Dim f, fMaxValue As Float
  Dim hSeries As _CSerie
  Dim i As Integer
  
  For Each hSeries In Chart
    f = 0
    For i = 0 To Chart.Count - 1
      f += hSeries[i]
    Next
    If fMaxValue < f Then fMaxValue = f
  Next
  Return fMaxValue
End



Public Function DrawChartAxes(oChart As Chart, hChartRect As CRect, fMinValue As Float, fMaxValue As Float, Optional iAlign As Integer) As CPoint
  Dim fTabPos As Float
  Dim i, iStaticSpace As Integer
  Dim fXUnit, fYUnit As Float
  Dim hPoint As CPoint
  Dim f As Float
  Dim fStep As Float
  Dim fMultiple As Float
  Dim oSerie As _CSerie
    'Draw the Y axe
  iStaticSpace = 5 * oChart._fProportionnal
  Draw.Line(hChartRect.Left, hChartRect.Top, hChartRect.Left, hChartRect.Bottom)
  
  fYUnit = (hChartRect.Bottom - hChartRect.Top) / (fMaxValue)
  
  fMultiple = Round(fMaxValue / 100)
  If fMultiple = 0 Then fMultiple = 1
  If fMaxValue > 1 Then 
    
    If fMaxValue / fMultiple < 10 Then 
      fStep = 0.5 * fMultiple
    Else If fMaxValue / fMultiple < 25 Then 
      fStep = 1 * fMultiple
    Else If fMaxValue / fMultiple < 50 Then 
      fStep = 2 * fMultiple
    Else If fMaxValue / fMultiple < 75 Then 
      fStep = 3 * fMultiple
    'ELSE IF fMaxValue / fMultiple < 90 THEN 
      'fStep = 4 * fMultiple
    Else If fMaxValue / fMultiple <= 100 Then 
      fStep = 5 * fMultiple
    Endif
    
Endif
  
  Draw.Font.Size = Chart.YAxe.Font.Size * Chart._fProportionnal  
  For f = 0 To fMaxValue Step fStep 'Round(fMaxValue / 20)
    'Position du taquet
    fTabPos = hChartRect.Bottom - (fYUnit * f)
    'Dessine les intervalles Verticaux
    If Chart.YAxe.ShowIntervalLines Then Draw.Line(hChartRect.Left, fTabPos, hChartRect.Right, fTabPos)
    'Dessine l'étiquette
    If Chart.YAxe.Visible Then 
      'Dessine le taquet

      Draw.Line(hChartRect.Left - iStaticSpace, fTabPos, hChartRect.Left, fTabPos)
      Draw.Text(f, hChartRect.Left - iStaticSpace * oChart._fProportionnal - Draw.TextWidth(f & "  "), fTabPos - Draw.Font.Height() / 2)
    Endif
  Next
  
  'IF $iType = ChartType.AreaPercent THEN fMaxVal = GetChartMaxCumulateValue(Chart)
  
  
  'Draw the X axe
  Draw.Line(hChartRect.Left, hChartRect.Bottom, hChartRect.Right, hChartRect.Bottom)
  
  If iAlign = Align.Center Then 
    fXUnit = ((hChartRect.Right - hChartRect.Left) / (Chart.Count + 1)) / Chart.CountDataSets
  Else 
    fXUnit = ((hChartRect.Right - hChartRect.Left) / (oChart.Count - 1))
  Endif
  fTabPos = hChartRect.Left 
  If iAlign = Align.Center Then 
  Draw.Font.Size = Chart.XAxe.Font.Size * Chart._fProportionnal
  For Each oSerie In Chart
      fTabPos += fXUnit * (Chart.Count + 1)
        Draw.Line(fTabPos, hChartRect.Bottom, fTabPos, hChartRect.Bottom + iStaticSpace)
      If oChart.XAxe.Visible Then 
        
        Draw.Text(oSerie.Text, fTabPos - (fXUnit * (Chart.Count + 1)) / 2 - Draw.TextWidth(oSerie.Text) / 2, hChartRect.Bottom + iStaticSpace, Align.Center)
      Endif
  Next
  Else
  For i = 0 To Chart.Count - 1
  
     '* '(Chart.Count + 1)
   
    

    Draw.Line(fTabPos, hChartRect.Bottom, fTabPos, hChartRect.Bottom + 2 * oChart._fProportionnal)
    If oChart.XAxe.Visible Then Draw.Text(Chart.Headers[i], fTabPos - Draw.TextWidth(Chart.Headers[i]) / 2, hChartRect.Bottom + iStaticSpace, Align.Center)
    fTabPos += fXUnit

  Next
Endif
  hPoint = New CPoint(fXUnit, fYUnit)
  Return hPoint
End


Public Sub DrawSymbol(iType As Integer, X As Integer, Y As Integer)
  Dim ariSymbol As Integer[]
  Dim iStaticSpace As Integer = 10 * Chart._fProportionnal
  X -= iStaticSpace / 2
  Y -= iStaticSpace / 2
  Select Case iType
    Case 0 'carré
     ariSymbol = [X, Y, X + iStaticSpace, Y, X + iStaticSpace, Y + iStaticSpace, X, Y + iStaticSpace]
     Draw.Polygon(ariSymbol)
    Case 1 'cercle
      Draw.Circle(X + iStaticSpace / 2, Y + iStaticSpace / 2, iStaticSpace / 2)
    Case 2 'Triangle
      ariSymbol = [X + CInt(iStaticSpace / 2), Y, X + iStaticSpace, Y + iStaticSpace, X, Y + iStaticSpace]
      Draw.Polygon(ariSymbol)
    Case 3 'TriangleInverse
      ariSymbol = [X + CInt(iStaticSpace / 2), Y + iStaticSpace, X + iStaticSpace, Y, X, Y]
      Draw.Polygon(ariSymbol)
    Case 4 'sablier
      ariSymbol = [X, Y, X + iStaticSpace, Y, X, Y + iStaticSpace, X + iStaticSpace, Y + iStaticSpace]
      Draw.Polygon(ariSymbol)
    Case 5 'sablierH
      
  End Select
  
End

Public Function DrawVertChartAxes(oChart As Chart, hChartRect As CRect, fMinValue As Float, fMaxValue As Float, Optional iAlign As Integer) As CPoint
  Dim fTabPos As Float
  Dim i, iStaticSpace As Integer
  Dim fXUnit, fYUnit As Float
  Dim hPoint As CPoint
  Dim f As Float
  Dim fStep As Float
  Dim fMultiple As Float
  Dim oSerie As _CSerie
    'Draw the Y axe
  iStaticSpace = 5 * oChart._fProportionnal
  Draw.Line(hChartRect.Left, hChartRect.Top, hChartRect.Left, hChartRect.Bottom)
  
  fYUnit = (hChartRect.Right - hChartRect.Left) / (fMaxValue)
  
  fMultiple = Round(fMaxValue / 100)
  If fMultiple = 0 Then fMultiple = 1
  If fMaxValue > 1 Then 
    
    If fMaxValue / fMultiple < 10 Then 
      fStep = 0.5 * fMultiple
    Else If fMaxValue / fMultiple < 25 Then 
      fStep = 1 * fMultiple
    Else If fMaxValue / fMultiple < 50 Then 
      fStep = 2 * fMultiple
    Else If fMaxValue / fMultiple < 75 Then 
      fStep = 3 * fMultiple
    'ELSE IF fMaxValue / fMultiple < 90 THEN 
      'fStep = 4 * fMultiple
    Else If fMaxValue / fMultiple <= 100 Then 
      fStep = 5 * fMultiple
    Endif
    
Endif
  
  Draw.Font.Size = Chart.XAxe.Font.Size * Chart._fProportionnal
  For f = 0 To fMaxValue Step fStep 'Round(fMaxValue / 20)
    'Position du taquet
    fTabPos = hChartRect.Left + (fYUnit * f)
    
    'Draw.Line(hChartRect.Left - iStaticSpace, fTabPos, hChartRect.Left, fTabPos)
    'Dessine les intervalles Verticaux
    If Chart.YAxe.ShowIntervalLines Then Draw.Line(fTabPos, hChartRect.Bottom, fTabPos, hChartRect.Top)
    'Dessine l'étiquette
    'Draw.Text(f, hChartRect.Left - iStaticSpace * oChart._fProportionnal - Draw.TextWidth(f & "  "), fTabPos - Draw.Font.Height() / 2)
    If Chart.XAxe.Visible Then 
      
      Draw.Text(f, fTabPos - Draw.Font.Width(f) / 2, hChartRect.Bottom + iStaticSpace * oChart._fProportionnal)
      'Dessine le taquet
      Draw.Line(fTabPos, hChartRect.Bottom - iStaticSpace, fTabPos, hChartRect.Bottom)
    Endif
  Next
  
  'If $iType = ChartType.AreaPercent Then fMaxVal = GetChartMaxCumulateValue(Chart)
  
  
 'Draw the X axe
 Draw.Line(hChartRect.Left, hChartRect.Bottom, hChartRect.Right, hChartRect.Bottom)
 
 If iAlign = Align.Center Then 
   fXUnit = ((hChartRect.Bottom - hChartRect.Top) / (oChart.Count + 1)) / Chart.CountDataSets
 Else 
   fXUnit = ((hChartRect.Bottom - hChartRect.Top) / (oChart.Count - 1))
 Endif
 fTabPos = hChartRect.Bottom
 If iAlign = Align.Center Then 
 Draw.Font.Size = Chart.YAxe.Font.Size * Chart._fProportionnal
 For Each oSerie In Chart
      
     fTabPos -= fXUnit * (Chart.Count + 1)
       Draw.Line(hChartRect.Left, fTabPos, hChartRect.Left - iStaticSpace, fTabPos)
     If oChart.YAxe.Visible Then Draw.Text(oSerie.Text, hChartRect.Left - Draw.TextWidth(oSerie.Text) - iStaticSpace, fTabPos + (fXUnit * (Chart.Count + 1)) / 2 + Draw.TextHeight(oSerie.Text) / 2)
 Next
 Else
 For i = 0 To Chart.Count - 1
 
    '* '(Chart.Count + 1)
  
   
 
   Draw.Line(fTabPos, hChartRect.Bottom, fTabPos, hChartRect.Bottom + 2 * oChart._fProportionnal)
   If oChart.YAxe.Visible Then Draw.Text(Chart.Headers[i], fTabPos - Draw.TextWidth(Chart.Headers[i]) / 2, hChartRect.Bottom + iStaticSpace, Align.Center)
   fTabPos += fXUnit
 
 Next
Endif
  hPoint = New CPoint(fXUnit, fYUnit)
  Return hPoint
End


Public Function GetChartMaxLenLabel(oChart As Chart) As String
  
  Dim hSeries As _CSerie
  Dim s As String
  Dim sCurMax As String
  
  sCurMax = 0
  For Each hSeries In oChart
    If Len(hSeries.Text) > Len(sCurMax) Then sCurMax = hSeries.Text
  Next
  Return sCurMax
  
End

