' Gambas module file

Public Function GetNullVariant() As Variant

  Return Null

End

Public Function GetNullObject() As Object

  Return Null

End

Public Sub Main2()

  Dim hURL As URL

  hURL = URL.FromString("http://localhost/guygle/find?query=ordre+de+travail+avec+interventions+dont+la+date+planifiée+est+comprise+entre+le+01%2F03%2F2017+et+31%2F03%2F2017+et+type+est+Campagne+dont+agence+est+AG.CIG.GONESSE&format=json&test#f5")
  
  Print hURL.Query["query"]
  
  Print hURL.ToString()

End


Public Sub Main()

End
