' Gambas module file

Public Const TYPE_NATIVE As Integer = 0
Public Const TYPE_CLASS As Integer = 1
Public Const TYPE_CONTROL As Integer = 2
Public Const TYPE_SYMBOL As Integer = 3
Public Const TYPE_EVENT As Integer = 4
Public Const TYPE_KEYWORD As Integer = 5
Public Const TYPE_SPECIAL As Integer = 6

Private Const ROOT_URL As String = "http://gambasdoc.org/help"

Public $PopupHelpCache As Collection

Private Sub GetPath(sPath As String) As String
  
  sPath = Replace(sPath, "/gb+gui/", "/gb+qt/")
  sPath = Replace(sPath, "/gb+gtk/", "/gb+qt/")
  Return System.Path &/ "share/gambas" & CStr(System.Version) &/ "help" &/ sPath
End


Public Sub Open()

  Dim sTool As String = FToolBox.GetTool()
  
  If sTool Then 
    GotoClass(CComponent.Classes[sTool].Component, sTool)
    FToolBox.SetTool
  Else
    Project.OpenWebPage(GetPath("tree/index.html"))
  Endif

End

Private Sub FormatName(sName As String) As String

  sName = LCase(sName)
  sName = Replace(sName, "_", "+")
  sName = Replace(sName, "/.", "/_")
  sName = Replace(sName, "/+", "/_")
  sName = Replace(sName, ".", "+")
  sName = Replace(sName, ":", "+")
  
  Return sName
  
End

Private Sub GetLanguage() As String
  
  Dim sLang As String = System.Language
  Dim iPos As Integer
  
  iPos = InStr(sLang, ".")
  If iPos Then sLang = Left$(sLang, iPos - 1)
  Return sLang
  
End


Public Sub GotoSymbol(hSymbol As CSymbolInfo)
  
  Dim sLink As String
  Dim sName As String
  Dim sComp As String
  
  sName = LCase(hSymbol.Name)
  If Right(sName) = "$" Then sName = Left(sName, -1)
  If hSymbol.Component = "gb" And If hSymbol.Class = "." Then
    sLink = "help/lang"
  Else
    sLink = "help/comp"
    sComp = hSymbol.Component
    If sComp = "gb.qt4" Or If sComp = "gb.gtk" Or If sComp = "gb.gui" Then sComp = "gb.qt"
    sLink &= "/" & sComp
    If hSymbol.Class <> "." Then sLink &= "/" & LCase(hSymbol.Class)
  Endif

  sLink &/= sName '& ".html"
  'sLink = FormatName(sLink)
  
  If Exist(GetPath(FormatName(sLink)) & ".html")
    Project.OpenWebPage(GetPath(FormatName(sLink)) & ".html")
  Else
    Project.OpenWebPage("http://gambasdoc.org" &/ sLink & "?v3&" & GetLanguage())
  Endif
  
End



Public Sub GotoComponent(sComp As String)
  
  Dim sLink As String
  
  sLink = "help/comp" &/ FormatName(sComp)
  Project.OpenWebPage(GetPath(sLink) & ".html")
  
End

Public Sub GotoClass(sComp As String, sClass As String)
  
  Dim sLink As String
  
  sLink = "help/comp" &/ FormatName(sComp) &/ FormatName(sClass)
  Project.OpenWebPage(GetPath(sLink) & ".html")
  
End

Public Function GotoKeyword(sName As String, Optional sName2 As String) As Boolean

  Dim sPath As String

  If sName2 Then
    If Not GotoKeyword(sName2) Then Return
  Endif

  If Right(sName) = "$" Then sName = Left$(sName, -1)

  sPath = GetPath("help/lang" &/ LCase(sName)) & ".html"
  If Not Exist(sPath) Then Return True
  Project.OpenWebPage(sPath)
  
Catch

  Return True

End

Public Function GotoDatatype(sName As String) As Boolean

  Dim sPath As String

  sPath = GetPath("help/lang/type" &/ LCase(sName)) & ".html"
  If Not Exist(sPath) Then Return True
  Project.OpenWebPage(sPath)
  
Catch

  Return True

End

Public Function GetSymbolHelpPath(hSymbol As CSymbolInfo) As String
  
  Dim sLink As String
  Dim sName As String
  Dim Result As String
  Dim sComp As String
  
  sName = LCase(hSymbol.Name)
  
  If hSymbol.Component = "gb" And If hSymbol.Class = "." Then
    sLink = "help/lang"
  Else
    sLink = "help/comp"
    sComp = hSymbol.Component
    If sComp = "gb.qt4" Or If sComp = "gb.gtk" Or If sComp = "gb.gui" Then sComp = "gb.qt"
    sLink &= "/" & sComp
    If hSymbol.Class <> "." Then sLink &= "/" & LCase(hSymbol.Class)
  Endif

  sLink &/= sName 
  sLink = FormatName(sLink)
  
  Result = GetPath(sLink) & ".html"
    
  If Not Exist(Result) Then 
    If hSymbol.Kind Then 
      'Try looking for the property in the object that this object inherits from
      hSymbol.Class = hSymbol.Kind
      hSymbol.Kind = ""
      Result = GetSymbolHelpPath(hsymbol)
      If Not Exist(Result) Then 
        'Try looking for the property in the Control object
        hSymbol.Class = "Control"
        Result = GetSymbolHelpPath(hsymbol)
      Endif   
    Endif 
  Endif 
  
  Result = LCase(Result)
  
  Return Result
  
End

Public Function GetSymbolHelpText(SymbolHelpPath As String) As String
  Dim HelpText As String
  
  'Check cache
  If Not $PopupHelpCache Then 
    'Create cache collection
    $PopupHelpCache = New Collection(gb.Text)
  Endif 
  
  If $PopupHelpCache.Exist(SymbolHelpPath) Then 
    Return $PopupHelpCache[SymbolHelpPath]
  Else 
    'Get from file
    HelpText = GetHelpTextFromFile(SymbolHelpPath)
    If HelpText Then 
      'Add to cache
      $PopupHelpCache[SymbolHelpPath] = HelpText 
      Return HelpText 
    Else 
      Return ""
    Endif 
  Endif 
    
End

Private Function GetHelpTextFromFile(SymbolHelpPath As String) As String
  
  Dim hFileIn As File
  Dim sInputLine As String
  Dim bGrabNextLine As Boolean
  Dim sResult As String
  Dim iPos As Integer
  Dim iPos2 As Integer
  Dim sWord As String
  
  bGrabNextLine = False
  sResult = ""

  hFileIn = Open SymbolHelpPath For Read

  Do While Not Eof(hFileIn)
    Line Input #hFileIn, sInputLine
    If bGrabNextLine Then 
    
      ' Remove links
      
      Do
        iPos = InStr(sInputLine, "<a ")
        If iPos = 0 Then Break 
        iPos2 = InStr(sInputLine, ">", iPos)
        If iPos2 = 0 Then Break 
        sInputLine = Left(sInputLine, iPos - 1) & Mid$(sInputLine, iPos2 + 1)
      Loop 
      
      sInputLine = Replace(sInputLine, "</a>", "")
    
      For Each sWord In Split(Trim(sInputLine), " \n")
        sResult &= " " & sWord
        iPos = InStr(sWord, ".")
        If iPos > 0 And If iPos = Len(sWord) Then Break
      Next
      If iPos > 0 And If iPos = Len(sWord) Then Break
    
    Else 
      If Right(RTrim(sInputLine), 6) = "</pre>" Then 
        bGrabNextLine = True
      Endif 
    Endif 
  Loop 
  
  sResult = Trim(sResult)
  
Finally 
  
  Try Close hFileIn
  
  If Not sResult Then 
    Return "<i>" & ("No help found.") & "</i>"
  Else
    Return sResult 
  Endif
  
End

Public Sub GetURL(Optional sPath As String) As String
  
  Return ROOT_URL &/ sPath
  
End


Public Sub GetHelpLanguage() As String
  
  Dim sLang As String = System.Language
  Dim iPos As Integer
  Dim sCar As String
  
  For iPos = 1 To Len(sLang)
    If Not IsLower(Mid$(sLang, iPos, 1)) Then Break
  Next
  
  Return Left$(sLang, iPos - 1)
  
End

Public Sub GetSymbolURL(sComponent As String, sClass As String, Optional sSymbol As String) As String
  
  Dim sPath As String
  Dim sName As String
  Dim sRes As String
  Dim sComp As String
  
  sPath = GetURL("comp")
  sComp = sComponent
  'If sComp = "gb.qt4" Or If sComp = "gb.gtk" Or If sComp = "gb.gui" Then sComp = "gb.qt"
  'If sComp = "gb.qt4.ext" Then sComp = "gb.qt.ext"
  sPath &/= LCase(sComp)
  sPath &/= Replace(LCase(sClass), "_", ".")
  
  If sSymbol Then
    sName = LCase(sSymbol)
    sName = Left(sName) & Replace(Mid$(sName, 2), "_", ".")
    sName = Replace(sName, ":", ".")
    sPath &/= sName
  Endif
    
  Return sPath & "?help&v3&" & GetHelpLanguage()
    
End

Public Sub GetClassURL(sComponent As String, sClass As String) As String
  
  Return GetSymbolURL(sComponent, sClass)
  
End

Public Sub GetLangURL(sSymbol As String) As String
  
  sSymbol = LCase(sSymbol)
  sSymbol = Replace(sSymbol, "$", "")
  If Right(sSymbol) = "?" Then sSymbol = "is" & Left(sSymbol, -1)
  
  Return GetURL("lang") &/ sSymbol & "?help&v3&" & GetHelpLanguage()
  
End

Public Sub GetSpecialURL(sSymbol As String) As String
  
  Return GetURL("lang") &/ "special" &/ Mid$(sSymbol, 2) & "?help&v3&" & GetHelpLanguage()
  
End

Public Sub InitWebViewWith(hWebView As WebView, iType As Integer, sSymbol As String, Optional sClass As String, Optional sMore As String)
  
  Dim cSymbol As Collection
  Dim hSymbol As CSymbolInfo
  Dim hClass As CClassInfo
  Dim sUrl As String
  Dim sHtml As String
  Dim sLang As String
  Dim iPos As Integer

  If Not hWebView Then 
    If Not FHelpBrowser.Visible Then Return
    hWebView = FHelpBrowser.webHelp
  Endif
  
  If iType = TYPE_NATIVE Then
  
    sUrl = MHelp.GetLangURL("type" &/ sSymbol)
    
  Else If iType = TYPE_KEYWORD Then
  
    sUrl = MHelp.GetLangURL(sSymbol)
    
  Else If iType = TYPE_SYMBOL Or If iType = TYPE_EVENT Then

    If iType = TYPE_EVENT Then
      iPos = InStr(sSymbol, "_")
      If iPos Then sSymbol = ":" & Mid$(sSymbol, iPos + 1)
    Endif
    Try hSymbol = CComponent.GetClassSymbols(sClass)[sSymbol]
    If hSymbol Then 
      If hSymbol.LineNumber Then 
        sHtml = hSymbol.GetHelpHTML()
      Else
        sUrl = hSymbol.GetHelpURL()
      Endif
    Endif
    
  Else If iType = TYPE_CLASS Or If iType = TYPE_CONTROL Then
  
    Try hClass = CComponent.Classes[sSymbol]
    If hclass Then 
      sUrl = hClass.GetHelpURL()
    Else If Project.GetClasses().Exist(sSymbol) Then
      sHtml = GetProjectClassHelpHTML(sSymbol)
    Endif
  Else If iType = TYPE_SPECIAL Then
      
    sUrl = MHelp.GetSpecialURL(sSymbol)
    
  Endif
  
  
  
  If sUrl Then
    If sMore Then sUrl &= "&" & sMore
    If hWebView.Url = sUrl Then Return
  Endif

  hWebView.Stop
  If sUrl Then
    hWebView.Url = sUrl
  Else If sHtml Then
    hWebView.Html = sHtml
  Else
    hWebView.HTML = "<html><body><h2>" & ("No help found.") & "</h2></body></html>"
  Endif
  hWebView.TextZoom = 0.8
    
End


Public Function GetProjectClassHelpHTML(sClass As String) As String
  
  Dim sResult, sHTML As String
  Dim hForm As FEditor
  Dim hedit As Editor
  'recuprerer l'aide
  hForm = Project.LoadFile(Project.FindPath(sClass))
  Try hEdit = hForm.Editor
  If Not hEdit Then Return  
  
  'demain j'inplante la suite
  sResult = hedit.Lines[0].Text
  
  sHTML = "<html><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">" & 
          "<link rel=\"stylesheet\" href=\"" & File.Dir(MHelp.GetURL()) & "/style.css\"></head><body class=\"none\">"
  sHTML &= "<div class\"frame\">"
  sHTML &= "<div class=\"title\">" & sClass & "</div>"
  sHTML &= "<pre class=\"syntax\">"
  sHTML &= "</pre><p>"
  sHTML &= sResult
  sHTML &= "</div></body></html>"
  Return sHTML
End