' Gambas module file

Private $cTr As New Collection

Public Sub Load()
  
  $cTr.Clear
  '{
  $cTr["No software patents in Europe!"] = ("No software patents in Europe!")
  $cTr["The greatest formula of the world!"] = ("The greatest formula of the world!")
  $cTr["Donate with PayPal"] = ("Donate with PayPal")
  $cTr["Flattr this"] = ("Flattr this")
  $cTr["Download"] = ("Download")
  $cTr["Release Notes"] = ("Release Notes")
  $cTr["Other downloads"] = ("Other downloads")
  $cTr["Browse source code"] = ("Browse source code")
  $cTr["Wiki"] = ("Wiki")
  $cTr["Bugtracker"] = ("Bugtracker")
  $cTr["Help"] = ("Help")
  $cTr["F.A.Q."] = ("F.A.Q.")
  $cTr["Compilation &amp; Installation"] = ("Compilation &amp; Installation")
  $cTr["Reporting a problem"] = ("Reporting a problem")
  $cTr["Mailing lists/Forums"] = ("Mailing lists/Forums")
  $cTr["Books"] = ("Books")
  $cTr["About"] = ("About")
  $cTr["Introduction"] = ("Introduction")
  $cTr["What is Gambas?"] = ("What is Gambas?")
  $cTr["Screenshots"] = ("Screenshots")
  $cTr["Benchmarks"] = ("Benchmarks")
  $cTr["License"] = ("License")
  $cTr["Hall Of Fame"] = ("Hall Of Fame")
  $cTr["English"] = ("English")
  $cTr["French"] = ("French")
  $cTr["Spanish"] = ("Spanish")
  $cTr["Catalonia"] = ("Catalonia")
  $cTr["German"] = ("German")
  $cTr["Dutch"] = ("Dutch")
  $cTr["Czech"] = ("Czech")
  $cTr["Turkish"] = ("Turkish")
  $cTr["Arabic"] = ("Arabic")
  $cTr["Korean"] = ("Korean")
  $cTr["Chinese"] = ("Chinese")
  '}
  
End

Public Sub _get(sStr As String) As String
  
  If $cTr.Exist(sStr) Then Return $cTr[sStr]
  Return sStr
  
End
