' Gambas module file

Private $cTr As New Collection

Public Sub Load()
  
  $cTr.Clear
  '{
  $cTr["Architecture"] = ("Architecture")
  $cTr["<b><i>Gambas</i></b> is a free development environment based on a <i>Basic</i> interpreter with object extensions, a bit like <i>Visual Basic&#8482;</i> (but it is <i><b>NOT</b></i> a clone&nbsp;!)."] = ("<b><i>Gambas</i></b> is a free development environment based on a <i>Basic</i> interpreter with object extensions, a bit like <i>Visual Basic&#8482;</i> (but it is <i><b>NOT</b></i> a clone&nbsp;!).")
  $cTr["Read the <a href=\"$(WIKI:/doc/intro)\">introduction</a> for more information."] = ("Read the <a href=\"$(WIKI:/doc/intro)\">introduction</a> for more information.")
  $cTr["Click there to see all news"] = ("Click there to see all news")
  $cTr["Download"] = ("Download")
  $cTr["Release Notes"] = ("Release Notes")
  $cTr["Donate with PayPal"] = ("Donate with PayPal")
  $cTr["Flattr this"] = ("Flattr this")
  $cTr["You can support <b><i>Gambas</i></b> by making a small donation with"] = ("You can support <b><i>Gambas</i></b> by making a small donation with")
  $cTr["or by using"] = ("or by using")
  $cTr["Hall Of Fame"] = ("Hall Of Fame")
  $cTr["Developers"] = ("Developers")
  $cTr["Developer"] = ("Developer")
  $cTr["Country"] = ("Country")
  $cTr["Working or have worked on..."] = ("Working or have worked on...")
  $cTr["If you are developing anything directly related to <b><i>Gambas</i></b> or its IDE, and not on the previous list, or if you find a mistake in this list, then write me! And explain me who you are and what you have done, so that I add you to the Hall Of Fame."] = ("If you are developing anything directly related to <b><i>Gambas</i></b> or its IDE, and not on the previous list, or if you find a mistake in this list, then write me! And explain me who you are and what you have done, so that I add you to the Hall Of Fame.")
  $cTr["Translations"] = ("Translations")
  $cTr["Language"] = ("Language")
  $cTr["Translator(s)"] = ("Translator(s)")
  $cTr["If you want to translate <b><i>Gambas</i></b>, write me so that I add you on the previous table, and read the <a href=\"$(WIKI:/howto/translate)\">How To</a> carefully."] = ("If you want to translate <b><i>Gambas</i></b>, write me so that I add you on the previous table, and read the <a href=\"$(WIKI:/howto/translate)\">How To</a> carefully.")
  $cTr["If you want to work on an already existing translation, contact the translators."] = ("If you want to work on an already existing translation, contact the translators.")
  $cTr["No software patents in Europe!"] = ("No software patents in Europe!")
  $cTr["The greatest formula of the world!"] = ("The greatest formula of the world!")
  $cTr["Browse source code"] = ("Browse source code")
  $cTr["Wiki"] = ("Wiki")
  $cTr["Documentation"] = ("Documentation")
  $cTr["Books"] = ("Books")
  $cTr["License"] = ("License")
  $cTr["Screenshots"] = ("Screenshots")
  $cTr["Mailing lists/Forums"] = ("Mailing lists/Forums")
  $cTr["All Release Notes"] = ("All Release Notes")
  $cTr["Bugtracker"] = ("Bugtracker")
  $cTr["Help"] = ("Help")
  $cTr["F.A.Q."] = ("F.A.Q.")
  $cTr["Compilation &amp; Installation"] = ("Compilation &amp; Installation")
  $cTr["Reporting a problem"] = ("Reporting a problem")
  $cTr["About"] = ("About")
  $cTr["Introduction"] = ("Introduction")
  $cTr["What is Gambas?"] = ("What is Gambas?")
  $cTr["English"] = ("English")
  $cTr["French"] = ("French")
  $cTr["Spanish"] = ("Spanish")
  $cTr["Catalonia"] = ("Catalonia")
  $cTr["German"] = ("German")
  $cTr["Dutch"] = ("Dutch")
  $cTr["Czech"] = ("Czech")
  $cTr["Turkish"] = ("Turkish")
  $cTr["Arabic"] = ("Arabic")
  $cTr["Korean"] = ("Korean")
  $cTr["Chinese"] = ("Chinese")
  $cTr["Czech Republic"] = ("Czech Republic")
  $cTr["Home"] = ("Home")
  $cTr["F. A. Q."] = ("F. A. Q.")
  $cTr["Resources"] = ("Resources")
  $cTr["Bug tracker"] = ("Bug tracker")
  $cTr["Distributions &amp; O.S."] = ("Distributions &amp; O.S.")
  $cTr["Some Applications"] = ("Some Applications")
  $cTr["Wiki Encyclopaedia"] = ("Wiki Encyclopaedia")
  $cTr["Browse Source Code"] = ("Browse Source Code")
  '}
  
End

Public Sub _get(sStr As String) As String
  
  If $cTr.Exist(sStr) Then Return $cTr[sStr]
  Return sStr
  
End
