' Gambas module file

Private $cTr As New Collection

Public Sub Load()
  
  $cTr.Clear
  '{
  $cTr["Screenshots"] = ("Screenshots")
  $cTr["Home"] = ("Home")
  $cTr["Introduction"] = ("Introduction")
  $cTr["What is Gambas?"] = ("What is Gambas?")
  $cTr["F. A. Q."] = ("F. A. Q.")
  $cTr["Download"] = ("Download")
  $cTr["Readme"] = ("Readme")
  $cTr["Reporting a problem"] = ("Reporting a problem")
  $cTr["Resources"] = ("Resources")
  $cTr["Distributions &amp; O.S."] = ("Distributions &amp; O.S.")
  $cTr["Links"] = ("Links")
  $cTr["Mailing lists/Forums"] = ("Mailing lists/Forums")
  $cTr["Documentation"] = ("Documentation")
  $cTr["Books"] = ("Books")
  $cTr["Getting Started"] = ("Getting Started")
  $cTr["License"] = ("License")
  $cTr["Wiki Encyclopaedia"] = ("Wiki Encyclopaedia")
  $cTr["Developer"] = ("Developer")
  $cTr["Architecture"] = ("Architecture")
  $cTr["Browse Source Code"] = ("Browse Source Code")
  $cTr["Hall Of Fame"] = ("Hall Of Fame")
  $cTr["Road Map"] = ("Road Map")
  $cTr["The future Gambas 3 icon (maybe)"] = ("The future Gambas 3 icon (maybe)")
  $cTr["English version"] = ("English version")
  $cTr["French version"] = ("French version")
  $cTr["Developers"] = ("Developers")
  $cTr["Country"] = ("Country")
  $cTr["Working or have worked on..."] = ("Working or have worked on...")
  $cTr["Translations"] = ("Translations")
  $cTr["Language"] = ("Language")
  $cTr["Translator(s)"] = ("Translator(s)")
  $cTr["<img src=\"warning.png\" align=center>&nbsp;READ THESE <a href=\"http://gambasdoc.org/help/readme?view\">IMPORTANT NOTES</a> AND <a href=\"http://gambasdoc.org/help/install?view\">THIS PAGE</a> FIRST."] = ("<img src=\"warning.png\" align=center>&nbsp;READ THESE <a href=\"http://gambasdoc.org/help/readme?view\">IMPORTANT NOTES</a> AND <a href=\"http://gambasdoc.org/help/install?view\">THIS PAGE</a> FIRST.")
  $cTr["Package"] = ("Package")
  $cTr["Version"] = ("Version")
  $cTr["Format"] = ("Format")
  $cTr["Current Developer Snapshots"] = ("Current Developer Snapshots")
  $cTr["Stable Version Source Packages"] = ("Stable Version Source Packages")
  $cTr["ChangeLog"] = ("ChangeLog")
  $cTr["Gambas Presentation"] = ("Gambas Presentation")
  $cTr["Presentation"] = ("Presentation")
  $cTr["Type"] = ("Type")
  $cTr["Binary Packages"] = ("Binary Packages")
  $cTr["Distribution"] = ("Distribution")
  $cTr["Packages"] = ("Packages")
  $cTr["Correctly packaged"] = ("Correctly packaged")
  $cTr["Last stable version is"] = ("Last stable version is")
  $cTr["<b><i>Gambas</i></b> is a free development environment based on a <i>Basic</i> interpreter with object extensions, a bit like <i>Visual Basic&#8482;</i> (but it is <i><b>NOT</b></i> a clone&nbsp;!)."] = ("<b><i>Gambas</i></b> is a free development environment based on a <i>Basic</i> interpreter with object extensions, a bit like <i>Visual Basic&#8482;</i> (but it is <i><b>NOT</b></i> a clone&nbsp;!).")
  $cTr["Read the <a href=\"introduction.html\">introduction</a> for more information."] = ("Read the <a href=\"introduction.html\">introduction</a> for more information.")
  $cTr["With <b><i>Gambas</i></b>, you can quickly design your program GUI with QT or GTK+, access MySQL, PostgreSQL, Firebird, ODBC and SQLite databases, pilot <i>KDE</i> applications with <i>DCOP</i>, translate your program into any language,   create network applications easily, make 3D OpenGL applications, make CGI web applications, and so on..."] = ("With <b><i>Gambas</i></b>, you can quickly design your program GUI with QT or GTK+, access MySQL, PostgreSQL, Firebird, ODBC and SQLite databases, pilot <i>KDE</i> applications with <i>DCOP</i>, translate your program into any language,   create network applications easily, make 3D OpenGL applications, make CGI web applications, and so on...")
  $cTr["You can support <b><i>Gambas</i></b> by making a small donation with"] = ("You can support <b><i>Gambas</i></b> by making a small donation with")
  $cTr["The greatest formula of the world!"] = ("The greatest formula of the world!")
  $cTr["No software patents in Europe!"] = ("No software patents in Europe!")
  $cTr["Where are you?"] = ("Where are you?")
  $cTr["Thanks for the support of gnuLinex!"] = ("Thanks for the support of gnuLinex!")
  $cTr["Latest News"] = ("Latest News")
  $cTr["Older News..."] = ("Older News...")
  $cTr["<b>Note:</b> This page needs a web browser that understands the CSS standard. If you use Internet Explorer 7 (it is just an example), you will see what I mean."] = ("<b>Note:</b> This page needs a web browser that understands the CSS standard. If you use Internet Explorer 7 (it is just an example), you will see what I mean.")
  $cTr["News Archive"] = ("News Archive")
  $cTr["Mailing lists &amp; Forums"] = ("Mailing lists &amp; Forums")
  '}
  
End

Public Sub _get(sStr As String) As String
  
  If $cTr.Exist(sStr) Then Return $cTr[sStr]
  Return sStr
  
End
